### ISSUE TITLE
ImportError: cannot import name 'SourceModel' from 'SourceIO.source_model'

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/SourceIO#1]
**Blender 2.80 Beta** [ Date: **2019-03-03** Hash: **ae977d13f8e9** ]
**SourceIO v3.3.5** https://github.com/REDxEYE/SourceIO/releases/download/3.3.5/SourceIO.zip

I don't know if it's too early to submit bug reports.
When attempting to import a MDL, I get the following error:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\__init__.py", line 50, in execute
    from . import mdl2model
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\mdl2model.py", line 16, in <module>
    from SourceIO.source_model import SourceModel
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\source_model.py", line 3, in <module>
    from SourceIO import qc_renerator
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\qc_renerator.py", line 9, in <module>
    from SourceIO.source_model import SourceModel
ImportError: cannot import name 'SourceModel' from 'SourceIO.source_model' (C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\source_model.py)

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
Recursive import.... Ops, gonna fix it asap

**Comment by REDxEYE** [comment]
Should be fixed now

**Comment by Gnates** [comment]
Yes, it's fixed now. You may close this.

**Off topic :**
Is there an estimated time for when we will be able to import older MDL versions, like the Postal 3 model mentioned here? https://github.com/REDxEYE/io_mesh_SourceMDL/issues/9

**Comment by REDxEYE** [comment]
io_mesh_SourceMDL won't be updated anymore. 
SourceIO have v48,v49,v53 support rn, also SourceIO will be now all-in-one tool
