### ISSUE TITLE
Error when writing QC file: 'SourceMdlBone' object has no attribute 'poseToBoneColumn0'

### ISSUE THREAD

**Issue by RenaKunisaki** [REDxEYE/SourceIO#12]
When importing a model:

```
Traceback (most recent call last):
  File "/home/rena/.config/blender/2.80/scripts/addons/SourceIO/__init__.py", line 64, in execute
    qc.write_models(qc_file)
  File "/home/rena/.config/blender/2.80/scripts/addons/SourceIO/mdl/qc_generator.py", line 48, in write_models
    self.write_model(fileh, bp, bp.models[0])
  File "/home/rena/.config/blender/2.80/scripts/addons/SourceIO/mdl/qc_generator.py", line 81, in write_model
    bone.poseToBoneColumn0,
AttributeError: 'SourceMdlBone' object has no attribute 'poseToBoneColumn0'

location: <unknown location>:-1
```

Despite the error, the model is imported OK.

**Comment by REDxEYE** [comment]
Fixed in [e9714b0df85554e026f659a3840705c330b7a75a](https://github.com/REDxEYE/SourceIO/commit/e9714b0df85554e026f659a3840705c330b7a75a)
