### ISSUE TITLE
Import material incorrectly.

### ISSUE THREAD

**Issue by Xiarno** [REDxEYE/SourceIO#124]
I'm trying to import this: https://sfmlab.com/project/27936/

However, the material seems to not import correctly, if at all. All I get is a green plane. 
![image](https://user-images.githubusercontent.com/24660485/153960679-ebb93b70-78df-4fbe-ab3d-ad4d2d25439e.png)

Using Blender 3.0.1, from the Steam installation.
Windows 10. 
Version of the SourceIO addon: 4.0.1

The models & material was put into the usermod folder of SFM.
The model that was imported for this attempts is "blood01-a"

Here's the entire console log:
```
Read prefs: C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\modules\bpy\utils\__init__.py", line 232, in register_module_call
    register()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\startup\MSPlugin\__init__.py", line 652, in register
    bpy.types.TOPBAR_MT_file_import.append(menu_func_import)
AttributeError: 'module' object has no attribute 'TOPBAR_MT_file_import'
Registered Enrich - add-on for visual compositing with 12 modules
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
saving prefs
saving prefs
saving prefs

 --------------------------------- VDB BEGINNING ---------------------------------
PILLOW HAS NOT BEEN INSTALLED

--------------------------------- TT BEGINNING ---------------------------------
botaniq install dir autodetected as E:\Blender\Addons\_data\addons\botaniq_full (big zip embedded)
animation_layers_updater addon: Verbose is enabled
animation_layers_updater addon: Read in JSON settings from file
traffiq install dir autodetected as E:\Blender\Addons\_data\addons\traffiq_lite (big zip embedded)
xps_tools updater verbose is enabled
xps_tools Updater: Read in JSON settings from file
register_class(...):
Warning: 'sourceio.utils' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'sourceio.placeholders' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'sourceio.skin_changer' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'SourceIO_UL_VPKDirList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'SourceIO_UL_FlexControllerList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'sourceio.flex_control_panel' does not contain '_PT_' with prefix and suffix
Registered nodes
Auto Reload --- All files modification time updated
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend' ok
Info: Preferences saved
Warning: property 'keep_running' not found in item 'OperatorProperties'
Warning: property 'do_search' not found in item 'OperatorProperties'
Warning: property 'keep_running' not found in item 'OperatorProperties'
Warning: property 'do_search' not found in item 'OperatorProperties'
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
Info: Updated sidebar tabs
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('hl2') provider for hl2
[INFO]--[ContentManager:register_content_provider]: Registered GameinfoContentProvider('left4dead2_movies') provider for left4dead2_movies
[INFO]--[ContentManager:register_content_provider]: Registered GameinfoContentProvider('tf') provider for tf
[INFO]--[ContentManager:register_content_provider]: Registered GameinfoContentProvider('tf_movies') provider for tf_movies
[INFO]--[ContentManager:register_content_provider]: Registered GameinfoContentProvider('usermod') provider for usermod
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('platform') provider for platform
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('workshop') provider for workshop
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_b.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_b.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_c.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_c.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_d.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_d.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_e.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_e.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_f.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_f.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_g.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_g.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_h.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_h.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got "'" at 3:29
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected "'", but got '"' at 3:64
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_a', expected VKVToken.NEWLINE in 'blood01' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got '\n' at 3:65
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_a', expected VKVToken.NEWLINE in 'blood01_alphatest' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got "'" at 4:25
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected "'", but got '"' at 4:58
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got '\n' at 4:59
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got "'" at 9:38
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected "'", but got '"' at 9:57
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:201: UserWarning: Expected '"', but got '\n' at 9:58
  warnings.warn(f'Expected {terminator!r}, but got {self.symbol !r} at {self._line}:{self._column}')
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_b.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_b', expected VKVToken.NEWLINE in 'blood01_b' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_b'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_b.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_b', expected VKVToken.NEWLINE in 'blood01_alphatest_b' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_b' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_b' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_b'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_c.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_c', expected VKVToken.NEWLINE in 'blood01_c' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_c'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_c.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_c', expected VKVToken.NEWLINE in 'blood01_alphatest_c' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_c' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_c' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_c'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_d.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_d', expected VKVToken.NEWLINE in 'blood01_d' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_d'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_d.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_d', expected VKVToken.NEWLINE in 'blood01_alphatest_d' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_d' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_d' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_d'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_e.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_e', expected VKVToken.NEWLINE in 'blood01_e' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_e'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_e.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_e', expected VKVToken.NEWLINE in 'blood01_alphatest_e' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_e' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_e' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_e'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_f.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_f', expected VKVToken.NEWLINE in 'blood01_f' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_f'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_f.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_f', expected VKVToken.NEWLINE in 'blood01_alphatest_f' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_f' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_f' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_f'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_g.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_g', expected VKVToken.NEWLINE in 'blood01_g' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_g'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_g.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_g', expected VKVToken.NEWLINE in 'blood01_alphatest_g' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_g' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_g' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_g'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_h.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_h', expected VKVToken.NEWLINE in 'blood01_h' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_h'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi's Effect Props\Blood\blood01_alphatest_h.vmt file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_TEX_h', expected VKVToken.NEWLINE in 'blood01_alphatest_h' at 3:64
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\Blood\\blood01_NRM', expected VKVToken.NEWLINE in 'blood01_alphatest_h' at 4:58
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
E:\Blender\Addons\_data\addons\SourceIO\library\utils\kv_parser.py:301: UserWarning: Trying to recover from unexpected token VKVToken.STRING:'s Effect Props\\EXP', expected VKVToken.NEWLINE in 'blood01_alphatest_h' at 9:57
  warnings.warn(f"Trying to recover from unexpected token {token}:{value!r}, expected {token_type} "
[INFO]--[Shaders::vertexlitgeneric:create_nodes]: Creating material 'blood01_alphatest_h'
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials\models\Ryu-Gi.vtf file

```

**Comment by REDxEYE** [comment]
SourceIO does not handle spaces in paths well

**Comment by Xiarno** [comment]
Where is the space that it doesn't handle very well ?

**Comment by REDxEYE** [comment]
`Ryu-Gi's Effect Props`

**Comment by Xiarno** [comment]
Then how do I rename it without the files breaking ?

**Comment by REDxEYE** [comment]
No idea

**Comment by Xiarno** [comment]
Then could you possibly give a workaround please?

**Comment by REDxEYE** [comment]
Should be now fixed
