### ISSUE TITLE
Opening DMX files gives an error

### ISSUE THREAD

**Issue by Dee-Kay47** [REDxEYE/SourceIO#128]
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\source1_operators.py", line 145, in execute
    load_session(directory / file.name, 1)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\source1\dmx\load_sfm_session.py", line 121, in load_session
    create_camera(camera)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\source1\dmx\load_sfm_session.py", line 38, in create_camera
    camera = bpy.data.cameras.new(name=dme_camera.name)
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
Session import is big **WIP**
