### ISSUE TITLE
Doesn't work on Blender 3.1

### ISSUE THREAD

**Issue by spriteclad** [REDxEYE/SourceIO#129]
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Python: Traceback (most recent call last):
  File "C:\Users\batte\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 55, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\batte\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 46, in import_model_from_full_path
    return import_model_from_files(str(name), mdl_path, vvd_file, vtx_file, vvc_file, scale, create_drives,
  File "C:\Users\batte\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 81, in import_model_from_files
    container = import_model_v49(mdl_file, vvd_file, vtx_file, None, scale, create_drives, re_use_meshes,
  File "C:\Users\batte\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\blender_bindings\source1\mdl\v49\import_mdl.py", line 217, in import_model
    mesh_data.polygons.foreach_set("use_smooth", np.ones(len(mesh_data.polygons)))
TypeError: couldn't access the py sequence

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
Update to master
