### ISSUE TITLE
SourceIO - Installation Instructions?

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/SourceIO#13]
Do you mind including instructions for installing the add-on in Blender 2.80? 
Tried installing from here: https://github.com/REDxEYE/SourceIO/archive/master.zip 

I get the following error when trying to activate the add-on: 
```
Traceback (most recent call last):
  File "/home/user/Downloads/Blender/blender-2.80-bb7b741d2f1c-linux-glibc217-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO-master/__init__.py", line 13, in <module>
    from .mdl import mdl2model
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO-master/mdl/mdl2model.py", line 12, in <module>
    from ..mdl.source_model import SourceModel
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO-master/mdl/source_model.py", line 4, in <module>
    from ..mdl import qc_generator
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO-master/mdl/qc_generator.py", line 5, in <module>
    from SourceIO.data_structures.mdl_data import SourceMdlBone
ModuleNotFoundError: No module named 'SourceIO'
```
**Blender v2.80 Beta**
Date: **2019-07-10 15:05**
Hash: **bb7b741d2f1c**

**Comment by Zyphre** [comment]
Rename the folder to: SourceIO

When you downloaded the master it kept "SourceIO-master" as the filename, the code is looking for "SourceIO"

**Comment by 0Curtain0** [comment]
@Zyphre Thanks, I did what you mentioned and I got the following error:
```
Traceback (most recent call last):
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/__init__.py", line 14, in <module>
    from .vtf.blender_material import BlenderMaterial
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/blender_material.py", line 5, in <module>
    from ..vtf.import_vtf import import_texture
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/import_vtf.py", line 6, in <module>
    from ..vtf.VTFWrapper import VTFLib
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 40, in <module>
    class VTFLib:
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 44, in VTFLib
    vtflib_cdll = cdll.LoadLibrary(vtf_lib_name)
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libVTFLib13.so: cannot open shared object file: No such file or directory
```
**Blender v2.80 Release Candidate 2**
**Ubuntu Linux 64bit**

**Comment by REDxEYE** [comment]
Ubuntu crash should be fixed now, VTF utilities just won't be available (no better solution yet)

**Comment by 0Curtain0** [comment]
@REDxEYE 
I'm getting a new error after attempting to activate the add-on:
```
Traceback (most recent call last):
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/__init__.py", line 15, in <module>
    from .vtf.blender_material import BlenderMaterial
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/blender_material.py", line 5, in <module>
    from ..vtf.import_vtf import import_texture
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/import_vtf.py", line 6, in <module>
    from ..vtf.VTFWrapper import VTFLib
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 40, in <module>
    class VTFLib:
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 44, in VTFLib
    vtflib_cdll = cdll.LoadLibrary(os.path.join(full_path, vtf_lib_name))
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/user/Downloads/Blender/blender-2.80rc2-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtxc_dxtn.so: cannot open shared object file: No such file or directory
```
**Blender v2.80 Release Candidate 2**
**Ubuntu Linux 64bit**
**SourceIO v3.5.0** 73cbae5

**Comment by mirh** [comment]
It activates just fine for me on windows and rc3. 
I don't even need to rename sourceio-master.zip.
