### ISSUE TITLE
Unable to import mdl files

### ISSUE THREAD

**Issue by hecent** [REDxEYE/SourceIO#130]
```
Python: Traceback (most recent call last):
  File "C:\Users\####\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\source1_operators.py", line 53, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\####\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\source1\mdl\model_loader.py", line 23, in import_model_from_full_path
  File "C:\Users\####\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\source1\mdl\model_loader.py", line 47, in import_model_from_files
  File "C:\Users\####\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\SourceIO\source1\mdl\v49\import_mdl.py", line 192, in import_model
TypeError: couldn't access the py sequence

location: <unknown location>:-1
```

I believe this issue is occurring because of the recent blender update

**Comment by REDxEYE** [comment]
Update to master version
