### ISSUE TITLE
Error on old model import

### ISSUE THREAD

**Issue by mirh** [REDxEYE/SourceIO#14]
```
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\__init__.py", line 61, in execute
    importer.load()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\mdl2model.py", line 63, in load
    self.model.read()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\source_model.py", line 47, in read
    self.mdl.read()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\mdl_readers\mdl_v48.py", line 14, in read
    self.read_bones()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\mdl_readers\mdl_v48.py", line 40, in read_bones
    SourceMdlBone().read(self.reader, self.file_data)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\data_structures\mdl_data.py", line 667, in read
    reader.read_ascii_string)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\byte_io_mdl.py", line 211, in read_from_offset
    raise OffsetOutOfBounds()
SourceIO-master.byte_io_mdl.OffsetOutOfBounds
```
[Sample](https://github.com/REDxEYE/SourceIO/files/3442492/_Valve.zip).

**Comment by REDxEYE** [comment]
Should be fixed in latest version

**Comment by mirh** [comment]
I mean, something gets imported now. 
But it's all a garbled mess. 
```
Traceback (most recent call last):
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\__init__.py", line 61, in execute
    importer.load()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\mdl2model.py", line 83, in load
    self.create_attachments()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO-master\mdl\mdl2model.py", line 443, in create_attachments
    empty.parent_bone = bone.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by mirh** [comment]
I'm getting this now
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO-master\__init__.py", line 70, in execute
    import_textures=self.import_textures
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO-master\mdl\mdl2model.py", line 42, in __init__
    working_directory if working_directory is not None else resolve_root_directory_from_file(path))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO-master\utilities\path_utilities.py", line 38, in resolve_root_directory_from_file
    return resolve_root_directory_from_file(path.parent)
  [Previous line repeated 989 more times]
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO-master\utilities\path_utilities.py", line 34, in resolve_root_directory_from_file
    path = Path(path)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\pathlib.py", line 983, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\pathlib.py", line 640, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\pathlib.py", line 633, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\pathlib.py", line 55, in parse_parts
    it = reversed(parts)
RecursionError: maximum recursion depth exceeded while calling a Python object

location: <unknown location>:-1
```

**Comment by mirh** [comment]
```
Traceback (most recent call last):
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\__init__.py", line 86, in execute
    importer.load(dont_build_mesh=False)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\mdl\mdl2model.py", line 80, in load
    self.model.read()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\mdl\source_model.py", line 51, in read
    self.mdl.read()
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\mdl\mdl_readers\mdl_v48.py", line 13, in read
    self.file_data.read(self.reader)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\data_structures\mdl_data.py", line 249, in read
    self.read_header02(reader)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\data_structures\mdl_data.py", line 415, in read_header02
    self.second_name = reader.read_from_offset(entry+self.name_offset,reader.read_ascii_string)
  File "C:\blenderfolder\2.80\scripts\addons\SourceIO\byte_io_mdl.py", line 211, in read_from_offset
    raise OffsetOutOfBounds()
SourceIO.byte_io_mdl.OffsetOutOfBounds

location: <unknown location>:-1
```
Even though some other models open now.

**Comment by REDxEYE** [comment]
version of mdl file?

**Comment by mirh** [comment]
It's still the same file of the first post.

**Comment by mirh** [comment]
*Still happens*

**Comment by mirh** [comment]
It doesn't actually throws an error any longer, but the mesh is just a garbled mess.

**Comment by mirh** [comment]
It's back at throwing this tbh..
```
Warning: 'source_io.utils' doesn't contain '_PT_' with prefix & suffix
Traceback (most recent call last):
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\vtx.py", line 26, in read
    body_part.read(self.reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\bodypart.py", line 20, in read
    model.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\model.py", line 20, in read
    model_lod.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\lod.py", line 23, in read
    mesh.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\mesh.py", line 24, in read
    strip_group.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\strip_group.py", line 59, in read
    strip.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\strip.py", line 40, in read
    assert self.bone_count < 255
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1_operators.py", line 51, in execute
    mdl, vvd, vtx = import_model(directory / file.name, vvd, vtx)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_model_import.py", line 110, in import_model
    vtx.read()
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\vtx.py", line 34, in read
    body_part.read(self.reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\bodypart.py", line 20, in read
    model.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\model.py", line 20, in read
    model_lod.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\lod.py", line 23, in read
    mesh.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\mesh.py", line 24, in read
    strip_group.read(reader)
  File "C:\blenderfolder\2.83\scripts\addons\SourceIO\source1\new_vtx\structs\strip_group.py", line 35, in read
    assert index_count % 3 == 0
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by REDxEYE** [comment]
New mdl parser only supports V48/V49
