### ISSUE TITLE
4.0.3 fails to enable on blender 3.3 - Linux

### ISSUE THREAD

**Issue by jurassicjordan** [REDxEYE/SourceIO#166]
Traceback (most recent call last):
  File "/home/jordancruz/Tools/Blender-Versions/Blender/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/SourceIO/__init__.py", line 18, in <module>
    from .blender_bindings.bindings import register, unregister
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/SourceIO/blender_bindings/bindings.py", line 30, in <module>
    from .operators.shared_operators import (SOURCEIO_PT_Utils,
ImportError: cannot import name 'SOURCEIO_PT_Scene' from 'SourceIO.blender_bindings.operators.shared_operators' (/home/jordancruz/.config/blender/3.3/scripts/addons/SourceIO/blender_bindings/operators/shared_operators.py)

OS: Linux
Blender Version: 3.3.0

**Comment by REDxEYE** [comment]
Try to install master branch

**Comment by REDxEYE** [comment]
Closing because no response
