### ISSUE TITLE
4.0.1+ fails to import mdl files on blender 3.3.0 - Linux

### ISSUE THREAD

**Issue by jurassicjordan** [REDxEYE/SourceIO#167]
Python: Traceback (most recent call last):
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/SourceIO-master/blender_bindings/operators/source1_operators.py", line 55, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/SourceIO-master/blender_bindings/source1/mdl/model_loader.py", line 31, in import_model_from_full_path
    assert vtx_file.exists(), f"failed to find vtx file {mdl_path.with_suffix('')}"
AttributeError: 'str' object has no attribute 'exists'

OS: Linux
Blender version: 3.3.0

**Comment by REDxEYE** [comment]
Please try using master version

**Comment by REDxEYE** [comment]
Closing because no response
