### ISSUE TITLE
Cannot enable addon: "ModuleNotFoundError: No module named 'SourceIO'

### ISSUE THREAD

**Issue by topplehat** [REDxEYE/SourceIO#172]
This is what I get when I try to enable it.
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\jayan\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\__init__.py", line 18, in <module>
    from .blender_bindings.bindings import register, unregister
  File "C:\Users\jayan\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\bindings.py", line 8, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "C:\Users\jayan\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\operators\flex_operators.py", line 5, in <module>
    from ...library.source1.mdl.structs.flex import FlexController
  File "C:\Users\jayan\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\source1\mdl\structs\__init__.py", line 2, in <module>
    from ....utils.byte_io_mdl import ByteIO
  File "C:\Users\jayan\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\utils\byte_io_mdl.py", line 10, in <module>
    from SourceIO.library.utils import IBuffer
ModuleNotFoundError: No module named 'SourceIO'
```

OS: Windows
Blender Version: 3.4.1
Addon Version: 4.0.4

Tried looking at others having this same issue, though they were all linux. My friend is also experiencing this on his end. What do I do? All I just wanted to do was import a model and this came to be alot more trouble than I anticipated.

**Comment by zararashigal** [comment]
Bump
