### ISSUE TITLE
AttributeError when trying to import Source 2 packed map (.vpk)

### ISSUE THREAD

**Issue by DeliDoggo24** [REDxEYE/SourceIO#181]
Blender version - 3.4
OS - Arch Linux (6.1.11-zen1-1-zen)
Add-on version - 5.0.1

```
Python: Traceback (most recent call last):
  File "/home/shay/.config/blender/3.4/scripts/addons/SourceIO/blender_bindings/operators/source2_operators.py", line 124, in execute
    load_map(model, ContentManager(), self.scale)
  File "/home/shay/.config/blender/3.4/scripts/addons/SourceIO/blender_bindings/source2/vwrld/loader.py", line 32, in load_map
    return import_world(world_resource, map_resource, cm, scale)
  File "/home/shay/.config/blender/3.4/scripts/addons/SourceIO/blender_bindings/source2/vwrld/loader.py", line 42, in import_world
    for scene_object in node_resource.get_scene_objects():
AttributeError: 'NoneType' object has no attribute 'get_scene_objects'

```

Source 1 maps import just fine, but I can't get these ones to work.

**Comment by REDxEYE** [comment]
Please upload console logs

**Comment by DeliDoggo24** [comment]
Sorry for late response @REDxEYE where would I find those? The info panel just shows that one error and I'm not familiar with using python in the interactive console. I tried googling but wasn't really sure what I'm looking for.

**Comment by REDxEYE** [comment]
start blender from bash and then you can copy logs from there
