### ISSUE TITLE
Failed to import .mdl meshes, only imported armature

### ISSUE THREAD

**Issue by EditaNEmilis** [REDxEYE/SourceIO#182]
Blender version - 3.4
OS - Windows 10
Add-on version - 5.0.1

```
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\MAT_MontyBody.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\MAT_BassGitar.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\MAT_MontyBody.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\MAT_MontyEye.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Body_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Gitar_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Eye_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour1.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour1_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour2.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour2_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour3.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
[INFO]--[ContentManager:find_file]: Requesting materials\models\tetTris\FNaF\SB\Monty\Hour3_MTL.vmt file
[DEBUG]--[ContentManager:find_file]: Found in workshop!
Traceback (most recent call last):
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 54, in import_model_from_full_path
    return import_model_from_files(str(name), file_list, scale,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 87, in import_model_from_files
    container = import_model_v49(file_list, scale, create_drives, re_use_meshes, unique_material_names)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\source1\mdl\v49\import_mdl.py", line 62, in import_model
    armature = create_armature(mdl, scale)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\source1\mdl\v44\import_mdl.py", line 66, in create_armature
    ref_animation = mdl.animations[0]
IndexError: list index out of range
```

_And the video of that happening.._

https://user-images.githubusercontent.com/107065286/220387645-7bbec584-8821-4fe8-a25e-ee62ea391676.mp4

**Comment by REDxEYE** [comment]
Fixed
