### ISSUE TITLE
"failed to find skybox material" error when attempting to import tf2 skybox

### ISSUE THREAD

**Issue by MrMage750** [REDxEYE/SourceIO#185]
I'm trying to import the dustbowl skybox for my session, but when I try to import it I get this line of code

Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 251, in execute
    load_skybox_texture(skybox_name[:-2], int(self.resolution))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\source1\vtf\__init__.py", line 23, in load_skybox_texture
    main_data, hdr_main_data, hdr_alpha_data = convert_skybox_to_equiangular(skyname, width)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\source1\vtf\cubemap_to_envmap.py", line 28, in convert_skybox_to_equiangular
    raise SkyboxException(f'Failed to find skybox material {skyname}{n}')
SourceIO-master.library.source1.vtf.cubemap_to_envmap.SkyboxException: Failed to find skybox material cloud_dustbowl_00ft

I tried importing other tf2 maps and got the same general error messages when I did so

**Comment by REDxEYE** [comment]
It's either really cannot find material or something else went wrong. Please post entire console log

**Comment by MrMage750** [comment]
> It's either really cannot find material or something else went wrong. Please post entire console log

wdym by the entire console log? are the logs I provided not everything?

**Comment by REDxEYE** [comment]
![image](https://user-images.githubusercontent.com/17544576/223544530-bd68b81c-f1bc-44d1-a074-add6b919eec6.png)
Yes, there should be much more logs in system console

**Comment by MrMage750** [comment]
Read prefs: C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Registered nodes
Read blend: C:\Users\Owner\Documents\sexysally1.blend
GPUTexture: Blender Texture Not Loaded!
{'angles': '0 271 0',
 'classname': 'info_player_teamspawn',
 'hammerid': '3',
 'origin': '-760 400 205'}
GLump "sprp" offset: 36 size: 3574
GLump "dprp" offset: 3610 size: 12
Failed to find AJACKS/AJACKS_GRASS01 material
Failed to find AJACKS/H_BLACKMARBLE material
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 251, in execute
    load_skybox_texture(skybox_name[:-2], int(self.resolution))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\source1\vtf\__init__.py", line 23, in load_skybox_texture
    main_data, hdr_main_data, hdr_alpha_data = convert_skybox_to_equiangular(skyname, width)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\source1\vtf\cubemap_to_envmap.py", line 36, in convert_skybox_to_equiangular
    raise SkyboxException(f'Failed to find skybox texture {texture_path}')
SourceIO-master.library.source1.vtf.cubemap_to_envmap.SkyboxException: Failed to find skybox texture skybox/sky_main01ft
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 251, in execute
    load_skybox_texture(skybox_name[:-2], int(self.resolution))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\source1\vtf\__init__.py", line 23, in load_skybox_texture
    main_data, hdr_main_data, hdr_alpha_data = convert_skybox_to_equiangular(skyname, width)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\source1\vtf\cubemap_to_envmap.py", line 28, in convert_skybox_to_equiangular
    raise SkyboxException(f'Failed to find skybox material {skyname}{n}')
SourceIO-master.library.source1.vtf.cubemap_to_envmap.SkyboxException: Failed to find skybox material cloud_dustbowl_00ft
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 251, in execute
    load_skybox_texture(skybox_name[:-2], int(self.resolution))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\blender_bindings\source1\vtf\__init__.py", line 23, in load_skybox_texture
    main_data, hdr_main_data, hdr_alpha_data = convert_skybox_to_equiangular(skyname, width)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO-master\library\source1\vtf\cubemap_to_envmap.py", line 28, in convert_skybox_to_equiangular
    raise SkyboxException(f'Failed to find skybox material {skyname}{n}')
SourceIO-master.library.source1.vtf.cubemap_to_envmap.SkyboxException: Failed to find skybox material cloud_dustbowl_00ft

apologies for the misunderstanding before, I don't have a lot of experience with coding yet

**Comment by REDxEYE** [comment]
So, from these little logs i see i can only say that either you didn't properly unpack skybox materials or something else
skybox files **must** be in materials/skybox/<skybox_name>

**Comment by MrMage750** [comment]
turns out importing them as vtfs did the trick
