### ISSUE TITLE
Create drivers gets python traceback error when importing some models.

### ISSUE THREAD

**Issue by SolidVault** [REDxEYE/SourceIO#198]
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 55, in import_model_from_full_path
    return import_model_from_files(str(name), file_list, scale,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 92, in import_model_from_files
    container = import_model_v49(file_list, scale, create_drives, re_use_meshes, unique_material_names,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\v49\import_mdl.py", line 199, in import_model
    create_flex_drivers(mesh_obj, mdl)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\v49\import_mdl.py", line 235, in create_flex_drivers
    left_controller = next(
StopIteration

Im getting this error when importing some mdl models.

**Comment by SolidVault** [comment]
When i do disable create drivers import i get a messed up model, on the old versions it used to import quite fine, but now it doesnt for some reason, im trying to import smugs trilla model.

**Comment by REDxEYE** [comment]
Disabling drivers only affects generation of flex rules in blender. I should not affect model

**Comment by REDxEYE** [comment]
That's expected, read model description
