### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/SourceIO#2]
**Blender 2.80 Beta** [ Date: **2019-03-03** Hash: **ae977d13f8e9** ]
**SourceIO v3.3.6** https://github.com/REDxEYE/SourceIO/releases/download/3.3.6/SourceIO.zip
 4c2752f

Attempting to import a MDL v48: https://sta.sh/09oqflbli8o
Please let me know if you're unable to download the model.
```
MDL file type ID: IDST
MDL file version: 48
MDL stored file name: "characters/postal_babe/postal_babe.mdl"
MDL stored file size: 250,960 bytes
MDL actual file size: 250,960 bytes
MDL checksum: 9925ED6E
```

When the model failed to import, the following error message appeared:
```
 Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\__init__.py", line 58, in execute
    importer.load()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\mdl2model.py", line 70, in load
    self.model.read()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\source_model.py", line 46, in read
    self.mdl.read()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\mdl_readers\mdl_v48.py", line 22, in read
    self.read_bone_flex_drivers()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\mdl_readers\mdl_v48.py", line 180, in read_bone_flex_drivers
    mouth.read(self.reader)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\data_structures\mdl_data.py", line 1458, in read
    self.bone = reader.read_int32()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\byte_io_mdl.py", line 175, in read_int32
    return self.read('i')
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\byte_io_mdl.py", line 159, in read
    return struct.unpack(t, self._read(size))[0]
struct.error: unpack requires a buffer of 4 bytes

location: <unknown location>:-1
```

**Comment by REDxEYE** [comment]
Update with full V48 support hasn't been put into "Releases" tab yet , clone repo if you want to test newest version

**Comment by REDxEYE** [comment]
Oooops, i forgot to push fix for v48 ._.

**Comment by Gnates** [comment]
Take your time :)

**Comment by Gnates** [comment]
3d17302
The recent commit appears to have broken something:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO-master\__init__.py", line 35, in execute
    from SourceIO.mdl import mdl2model
ModuleNotFoundError: No module named 'SourceIO'

location: <unknown location>:-1
```

I think the io_texture_VTF add-on experienced something similar.

**Comment by REDxEYE** [comment]
Rename SourceIO-master to SourceIO

**Comment by Gnates** [comment]
I unzipped SourceIO-master.zip, renamed SourceIO-master folder to SourceIO, then zipped the SourceIO folder.
I installed the SourceIO.zip (no errors), activated the add-on (no errors), then tried to import the mdl but received the following error:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\__init__.py", line 35, in execute
    from SourceIO.mdl import mdl2model
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\mdl\mdl2model.py", line 14, in <module>
    from SourceIO.mdl.vvd_readers.vvd_v4 import SourceVvdFile4
ModuleNotFoundError: No module named 'SourceIO.mdl.vvd_readers'

location: <unknown location>:-1
```

I noticed the contents of the SourceIO folder shows:
```
- data_structures (folder)
- mdl (folder)
- utilities (folder)
- .gitignore
- __init__.py
- byte_io_mdl.py
```
The last time the add-on worked, it had the following contents:
```
- __pycache__ (folder)
- data_structures (folder)
- mdl_readers (folder)
- utilities (folder)
- vtx_readers (folder)
- vvd_readers (folder)
- __init__.py
- byte_io_mdl.py
- cpy_everything.py
- mdl2model.py
- qc_renerator.py
- smd_generator.py
- source_model.py
```

Am I downloading from GitHub incorrectly?
I clicked on the **Clone or Download** button, then **Download ZIP**.

**Comment by REDxEYE** [comment]
Hm, weird, everything looks correct

**Comment by Gnates** [comment]
I will try downloading a new Blender 2.8 build and give you feedback soon.

**Comment by Gnates** [comment]
Tried a new build:
**Blender 2.80 Beta** [ Date: **2019-03-07** Hash: **a280867ac2ed** ]
Still getting same error.

I will wait for the next release download.

**Comment by REDxEYE** [comment]
Try new release 3.3.8

**Comment by Gnates** [comment]
Thanks, **v3.3.8** appears to be on the right track. 
However, **MDL v48** doesn't appear to import correctly:
- https://gfycat.com/zanyfittingicelandgull

**Comment by REDxEYE** [comment]
This is problem i know, LODs my addon does not resolve them correctly

**Comment by 0Curtain0** [comment]
**Dummiesman**, the author of the **RipImport** add-on for Blender, made a comment about something related to the way struct works: https://github.com/xpawelsky/RipImport/issues/1#issuecomment-537580855 

I am not 100% sure if this is related to the current issue, but I figured I should mention it since the issue is still open.

**Comment by 0Curtain0** [comment]
> This is the problem i know about, LODs my addon does not resolve them correctly 

@REDxEYE  I forgot to ask, do you want to open a separate issue for the LOD problem? 
This way it would be easier to track LOD and struct.error problem separately. 

I did a new test with a different SFM model: https://sfmlab.com/item/3709/ 
**Operating System: Pop!_OS 64bit** (Based on Ubuntu)
**Blender 2.81a** (non-Steam version / tar.bz2)
**SourceIO: 3.5.8**

On fresh Blender startup (Blender wasn't running before), I tried to import **mechari_female_beta_bigger4_edit.mdl**, and it imports successfully. 

I CTRL+Z to undo the import, and then import the **postal_babe.mdl** (from before). 
The **postal_babe.mdl** imports into Blender but has the LOD problem, as mentioned before, ok. 

I CTRL+Z again to undo the **postal_babe.mdl** import, and then import **mechari_female_beta_bigger4_edit.mdl** again, but this time I get the following error: 
```
Traceback (most recent call last):
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 55, in read
    SourceVtxBodyPart().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 135, in read
    self.vtx_models.append(SourceVtxModel().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 156, in read
    SourceVtxModelLod().read(reader, self))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 181, in read
    self.vtx_meshes.append(SourceVtxMesh().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 207, in read
    SourceVtxStripGroup().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 266, in read
    SourceVtxStrip().read(reader, self)
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 330, in read
    self.bone_count = reader.read_uint16()
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/byte_io_mdl.py", line 177, in read_uint16
    return self.read('H')
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/byte_io_mdl.py", line 158, in read
    return struct.unpack(t, self._read(size))[0]
struct.error: unpack requires a buffer of 2 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/__init__.py", line 86, in execute
    importer.load(dont_build_mesh=False)
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/mdl/mdl2model.py", line 80, in load
    self.model.read()
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/mdl/source_model.py", line 63, in read
    self.vtx.read()
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/mdl/vtx_readers/vtx_v7.py", line 17, in read
    self.vtx.read(self.reader)
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 63, in read
    SourceVtxBodyPart().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 135, in read
    self.vtx_models.append(SourceVtxModel().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 156, in read
    SourceVtxModelLod().read(reader, self))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 181, in read
    self.vtx_meshes.append(SourceVtxMesh().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 207, in read
    SourceVtxStripGroup().read(reader))
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 266, in read
    SourceVtxStrip().read(reader, self)
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/data_structures/vtx_data.py", line 330, in read
    self.bone_count = reader.read_uint16()
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/byte_io_mdl.py", line 177, in read_uint16
    return self.read('H')
  File "/home/user/.config/blender/2.81/scripts/addons/SourceIO/byte_io_mdl.py", line 158, in read
    return struct.unpack(t, self._read(size))[0]
struct.error: unpack requires a buffer of 2 bytes

location: <unknown location>:-1
```
Importing the **mechari_butt.mdl** appears to have no issues. 

I tried **File** - **New** - **General**, then tried to import the **mechari_female_beta_bigger4_edit.mdl** again, but similar error. 

It appears that the **mechari_female_beta_bigger4_edit.mdl** will import correctly again if I exit Blender and start it up again. 
However, if I import that **postal_babe.mdl** into Blender first, and then try to import the **mechari_female_beta_bigger4_edit.mdl**, the import will produce the error. 

I'm on 64bit Linux, so I have no idea if this can be understood by someone who doesn't use Linux, and I'm not 100% sure if this is a Linux only problem.

Anyway, I did mention before that there was another Blender add-on (RipImport) I was using that has a similar problem with struct.error, and a user named @luchador3d is trying to help debug it: 
- https://github.com/xpawelsky/RipImport/issues/1#issuecomment-552216569 

I recently started working on a SFM to Blender guide: [Blender - Play with SFM Models](https://open3dlab.com/tutorials/view/20/) 
but because of the current bugs that I'm experiencing on Linux, I won't be able to do some new demos for the guide.
