### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Gabriel804war** [REDxEYE/SourceIO#203]
Traceback (most recent call last):
  File "G:\SteamLibrary\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\glass\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceIO\__init__.py", line 14, in <module>
    from .blender_bindings.bindings import register, unregister
  File "C:\Users\glass\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceIO\blender_bindings\bindings.py", line 8, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "C:\Users\glass\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceIO\blender_bindings\operators\flex_operators.py", line 5, in <module>
    from ...library.source1.mdl.structs.flex import FlexController
  File "C:\Users\glass\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\SourceIO\library\source1\mdl\structs\flex.py", line 6, in <module>
    import numpy.typing as npt
ModuleNotFoundError: No module named 'numpy.typing'

**Comment by REDxEYE** [comment]
Use Blender 3.1 or newer

**Comment by NuketheYmap7** [comment]
hey im getting the same error with 3.5


Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO-master\blender_bindings\source1\mdl\model_loader.py", line 36, in import_model_from_full_path
    vtx_file = FileBuffer(find_vtx(mdl_path))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 310, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by REDxEYE** [comment]
It's not same error. You missing .vtx file. Source engine mode are made from 3 files: .mdl, .vtx, .vvd
