### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read_struct'

### ISSUE THREAD

**Issue by OsaedYahya** [REDxEYE/SourceIO#206]
I am getting this error while trying to import VMDL_C files from Dota 2 workshop tools that I extracted using gcfscape

Blender version: 3.5
Plugin version: 5.0.3

Python: Traceback (most recent call last):
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 50, in execute
    container = load_model(model_resource, self.scale, self.lod_mask,
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 69, in load_model
    armature = create_armature(resource, scale)
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 106, in create_armature
    s2_bones = resource.get_bones()
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\source2\resource_types\compiled_model_resource.py", line 18, in get_bones
    data, = self.get_data_block(block_name='DATA')
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 53, in get_data_block
    data_block = self.get_data_block(block_id=i)
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 45, in get_data_block
    data_block = data_block_class.from_buffer(MemoryBuffer(self._buffer.read(info_block.size)), self)
  File "C:\Users\ME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\source2\data_types\blocks\kv3_block.py", line 39, in from_buffer
    self.update(ntro.read_struct(buffer, self._get_struct(ntro)))
AttributeError: 'NoneType' object has no attribute 'read_struct'

**Comment by REDxEYE** [comment]
Please upload model file

**Comment by OsaedYahya** [comment]
> Please upload model file

This modal was extracted from the Dota 2 Workshop, I used the latest model to the game

**Comment by OsaedYahya** [comment]
> Please upload model file

This modal was extracted from the Dota 2 Workshop, I used the latest model to the game

**Comment by OsaedYahya** [comment]
> Please upload model file

This modal was extracted from the Dota 2 Workshop, I used the latest model to the game

**Comment by OsaedYahya** [comment]
> Please upload model file

This modal was extracted from the Dota 2 Workshop, I used the latest model to the game

**Comment by REDxEYE** [comment]
I don't have dota installed, so please upload the model file

**Comment by OsaedYahya** [comment]
https://file.io/rHpy48CCzwKC

**Comment by OsaedYahya** [comment]
Other model that worked is this
https://file.io/rHpy48CCzwKC

**Comment by REDxEYE** [comment]
SourceIO does not supported updated VKV3 version used in this models. Support will be added soon

**Comment by OsaedYahya** [comment]
Thank you, looking forward to it.
Is there anyway to install older models for this? I just want to create an STL file for 3d printing, I am not invested in animating/modifying

**Comment by REDxEYE** [comment]
Try to export model using VRF https://github.com/SteamDatabase/ValveResourceFormat

**Comment by OsaedYahya** [comment]
It's opening the model but I am new to this tool and I have no idea where to export the model

![image](https://github.com/REDxEYE/SourceIO/assets/69788216/00e4dac4-7127-4d8b-a832-1c41caf94829)

**Comment by OsaedYahya** [comment]
Wait, I am sorry. I had to open the pak file, it worked!! thank you so muchhhhh
