### ISSUE TITLE
Plugin will not install at all

### ISSUE THREAD

**Issue by yeenyeenyeen** [REDxEYE/SourceIO#207]
Attempting to install the latest version results in an error.

Blender version: 3.5.1
Plugin version: 5.0.3

Traceback (most recent call last):
  File "/usr/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/__init__.py", line 14, in <module>
    from .blender_bindings.bindings import register, unregister
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/blender_bindings/bindings.py", line 8, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/blender_bindings/operators/flex_operators.py", line 6, in <module>
    from .shared_operators import UITools
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/blender_bindings/operators/shared_operators.py", line 7, in <module>
    from ..source1.mdl.v44.import_mdl import import_static_animations
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/blender_bindings/source1/mdl/__init__.py", line 7, in <module>
    from ...shared.model_container import Source1ModelContainer
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/blender_bindings/shared/model_container.py", line 12, in <module>
    from ...library.source2.resource_types import CompiledModelResource
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/source2/__init__.py", line 29, in <module>
    from .resource_types import CompiledMorphResource, CompiledPhysicsResource
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/source2/resource_types/__init__.py", line 1, in <module>
    from .compiled_material_resource import CompiledMaterialResource
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/source2/resource_types/compiled_material_resource.py", line 3, in <module>
    from .resource import CompiledResource
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/source2/resource_types/resource.py", line 8, in <module>
    from ...shared.content_providers.content_manager import ContentManager
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/shared/content_providers/content_manager.py", line 11, in <module>
    from .content_provider_base import ContentProviderBase
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/shared/content_providers/content_provider_base.py", line 7, in <module>
    from ..app_id import SteamAppId
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/shared/app_id.py", line 5, in <module>
    class SteamAppId(IntEnum):
  File "/home/maxintosh/.config/blender/3.5/scripts/addons/SourceIO/library/shared/app_id.py", line 35, in SteamAppId
    def _create_pseudo_member_(cls, value):
  File "/usr/lib/python3.11/enum.py", line 379, in __setitem__
    raise ValueError(
ValueError: _sunder_ names, such as '_create_pseudo_member_', are reserved for future Enum use

**Comment by REDxEYE** [comment]
Update to master build
https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by REDxEYE** [comment]
It's the issue with mac/linux blender build using newer python version than windows
