### ISSUE TITLE
Unable to check SourceIO addon in UPBGE

### ISSUE THREAD

**Issue by EditaNEmilis** [REDxEYE/SourceIO#211]
I tried to check the recent master version of SourceIO in UPBGE (Uchronia Project Blender Game Engine). And yet it keep spitting out the console error.

This is the traceback console.
```
Traceback (most recent call last):
  File "C:\Users\raman\Downloads\UPBGE-0.30-windows-x86_64\UPBGE-0.30-windows-x86_64\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\raman\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\SourceIO-master\__init__.py", line 14, in <module>
    from .blender_bindings.bindings import register, unregister
  File "C:\Users\raman\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\SourceIO-master\blender_bindings\bindings.py", line 8, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "C:\Users\raman\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\SourceIO-master\blender_bindings\operators\flex_operators.py", line 5, in <module>
    from ...library.source1.mdl.structs.flex import FlexController
  File "C:\Users\raman\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\SourceIO-master\library\source1\mdl\structs\flex.py", line 48, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
```

**Comment by REDxEYE** [comment]
SourceIO requires at minimum blender 3.1

**Comment by EditaNEmilis** [comment]
Yes but I'm using the stable 0.3 build of UPBGE, unless I have to download the current 0.35 or wait for 0.4
