### ISSUE TITLE
Problem when trying to load entities on source map import.

### ISSUE THREAD

**Issue by sog76561198136342500** [REDxEYE/SourceIO#212]
Happens with various maps when I go and click load entity:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\operators\shared_operators.py", line 58, in execute
    content_manager.deserialize(bpy.context.scene.get('content_manager_data', {}))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\shared\content_providers\content_manager.py", line 260, in deserialize
    bsp = open_bsp(path)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\library\source1\bsp\bsp_file.py", line 14, in open_bsp
    assert Path(filepath).exists()
AssertionError

**Comment by REDxEYE** [comment]
Seems like original bsp file is gone or was moved after import

**Comment by sog76561198136342500** [comment]
I think you're right, I tried reimporting it again and I can now load the entities, thanks for the help.
