### ISSUE TITLE
Can't enable after install

### ISSUE THREAD

**Issue by oraknabo** [REDxEYE/SourceIO#216]
I'm on Blender 3.5.1 & Python 3.11 After installing the zip from Blender preferences, clicking the enable checkbox spits out these errors (w/ paths shortened):

> Traceback (most recent call last):  
  File "/usr/share/blender/3.5/scripts/modules/addon_utils.py", line 333, in enable  
    mod = __import__(module_name)  
          ^^^^^^^^^^^^^^^^^^^^^^^  
  File "[addon path]/SourceIO/__init__.py", line 14, in <module>  
    from .blender_bindings.bindings import register, unregister  
  File "[addon path]/SourceIO/blender_bindings/bindings.py", line 8, in <module>  
    from .operators.flex_operators import SourceIO_PG_FlexController  
  File "[addon path]/SourceIO/blender_bindings/operators/flex_operators.py", line 6, in <module>  
    from .shared_operators import UITools  
  File "[addon path]/SourceIO/blender_bindings/operators/shared_operators.py", line 7, in <module>  
    from ..source1.mdl.v44.import_mdl import import_static_animations  
  File "[addon path]/SourceIO/blender_bindings/source1/mdl/__init__.py", line 7, in <module>  
    from ...shared.model_container import Source1ModelContainer  
  File "[addon path]/SourceIO/blender_bindings/shared/model_container.py", line 12, in <module>  
    from ...library.source2.resource_types import CompiledModelResource  
  File "[addon path]/SourceIO/library/source2/__init__.py", line 29, in <module>  
    from .resource_types import CompiledMorphResource, CompiledPhysicsResource  
  File "[addon path]/SourceIO/library/source2/resource_types/__init__.py", line 1, in <module>  
    from .compiled_material_resource import CompiledMaterialResource  
  File "[addon path]/SourceIO/library/source2/resource_types/compiled_material_resource.py", line 3, in <module>  
    from .resource import CompiledResource  
  File "[addon path]/SourceIO/library/source2/resource_types/resource.py", line 8, in <module>  
    from ...shared.content_providers.content_manager import ContentManager  
  File "[addon path]/SourceIO/library/shared/content_providers/content_manager.py", line 11, in <module>  
    from .content_provider_base import ContentProviderBase  
  File "[addon path]/SourceIO/library/shared/content_providers/content_provider_base.py", line 7, in <module>  
    from ..app_id import SteamAppId  
  File "[addon path]/SourceIO/library/shared/app_id.py", line 5, in <module>  
    class SteamAppId(IntEnum):  
  File "[addon path]/SourceIO/library/shared/app_id.py", line 35, in SteamAppId  
    def _create_pseudo_member_(cls, value):  
  File "/usr/lib/python3.11/enum.py", line 379, in __setitem__  
    raise ValueError(  
ValueError: _sunder_ names, such as '_create_pseudo_member_', are reserved for future Enum use`

**Comment by oraknabo** [comment]
I saw a link to the newer zip that fixes this problem in a closed issue. Feel free to delete.

**Comment by Delgran** [comment]
I still got the problem.

![Screenshot 2023-11-25 102642](https://github.com/REDxEYE/SourceIO/assets/152001529/2fe059d4-c9da-4f94-89d6-f72f1ff80146)

**Comment by REDxEYE** [comment]
@Delgran What exactly you have? Exactly the same error? No, that's not possible, i have fixed it long time ago. Please provide logs/screenshots
