### ISSUE TITLE
Python Error when I try to import a model 

### ISSUE THREAD

**Issue by Cole1335** [REDxEYE/SourceIO#229]
When I choose my file and click "Import Source MDL File", this error appears: 

Python: Traceback (most recent call last):
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 51, in import_model_from_full_path
    return import_model_from_files(str(name), file_list, scale,
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 73, in import_model_from_files
    assert magic == b'IDST', f'Unknown Mdl magic "{magic}", expected "IDST"'
AssertionError: Unknown Mdl magic "b'DST0'", expected "IDST"

**Comment by REDxEYE** [comment]
Use Crowbar to unpack GMA files. GMAD has a bug that mangle files
