### ISSUE TITLE
Can't even enable the addon

### ISSUE THREAD

**Issue by TheTinkerer256** [REDxEYE/SourceIO#233]
When I try to check the box to enable the addon, it spits out this error:
`Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\[my name, censored]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SourceIO-master\__init__.py", line 14, in <module>
    from .blender_bindings.bindings import register, unregister
  File "C:\Users\[my name, censored]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SourceIO-master\blender_bindings\bindings.py", line 9, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "C:\Users\[my name, censored]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SourceIO-master\blender_bindings\operators\flex_operators.py", line 5, in <module>
    from ...library.source1.mdl.structs.flex import FlexController
  File "C:\Users\[my name, censored]\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SourceIO-master\library\source1\mdl\structs\flex.py", line 48, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'

`
Please help!

**Comment by REDxEYE** [comment]
![image](https://camo.githubusercontent.com/3015a7e2da07d81fd59d9b549ce1b3a6d6255701267ce2cd5ebcc0ab693ed293/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f426c656e6465722d2533453d5f332e312d6f72616e67653f6c6f676f3d626c656e646572266c6f676f436f6c6f723d7768697465)
