### ISSUE TITLE
AssertionError: Unknown Mdl magic "b'DST1'", expected "IDST"

### ISSUE THREAD

**Issue by cozerCode** [REDxEYE/SourceIO#241]
im trying to import an mdl file into blender but it keeps returning this error
```
Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 54, in import_model_from_full_path
    return import_model_from_files(str(name), file_list, scale,
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 76, in import_model_from_files
    assert magic == b'IDST', f'Unknown Mdl magic "{magic}", expected "IDST"'
AssertionError: Unknown Mdl magic "b'DST1'", expected "IDST"
```

**Comment by REDxEYE** [comment]
Don't use GMAD to unpack gma archives, use crowbar.
GMAD sometimes mangle files
