### ISSUE TITLE
S2FM error

### ISSUE THREAD

**Issue by S00pergang** [REDxEYE/SourceIO#242]
I downloaded a S2FM model from SFMLab, but when I try to import I get an error :

```Python: Traceback (most recent call last):
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 50, in execute
    container = load_model(model_resource, self.scale, self.lod_mask,
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 69, in load_model
    armature = create_armature(resource, scale)
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 106, in create_armature
    s2_bones = resource.get_bones()
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source2\resource_types\compiled_model_resource.py", line 18, in get_bones
    data, = self.get_data_block(block_name='DATA')
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 53, in get_data_block
    data_block = self.get_data_block(block_id=i)
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 45, in get_data_block
    data_block = data_block_class.from_buffer(MemoryBuffer(self._buffer.read(info_block.size)), self)
  File "■■■■■\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source2\data_types\blocks\kv3_block.py", line 39, in from_buffer
    self.update(ntro.read_struct(buffer, self._get_struct(ntro)))
AttributeError: 'NoneType' object has no attribute 'read_struct'
```

Strange thing is previous s2fm models by same user seem to work, but not the ones I've recently downloaded don't.

**Comment by S00pergang** [comment]
Nevermind, turns out I didn't have to latest version of the plugin. My bad.
