### ISSUE TITLE
Source Filmmaker map import missing textures

### ISSUE THREAD

**Issue by regex420** [REDxEYE/SourceIO#245]
All maps from tf, tf_movies, usermod, workshop don't load textures and have random pastel colors. Moving the sourcefilmmaker folder did nothing. Importing models works just fine. What am I doing wrong?

```
Report: Error
Python: Traceback (most recent call last):
  File "S:\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 141, in execute
    bsp_map.load_materials(self.use_bvlg)
  File "S:\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 185, in load_materials
    mat.create_material()
  File "S:\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "S:\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\source1_shaders\lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```

**Comment by kentuckyfriedmeerkat** [comment]
Some Blender Principled BDSF shader properties have [changed their key names](https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API) since the release of 4.0. This addon hasn't been updated to reflect this. I have a fork which fixes this (for my purposes) at kentuckyfriedmeerkat/SourceIO which you're welcome to refer to but I haven't submitted a PR because my knowledge of Blender doesn't run deep enough to fix it without breaking 3.x compatibility.

**Comment by regex420** [comment]
@kentuckyfriedmeerkat Thank you that was it. Didn't thought about Blender version

**Comment by REDxEYE** [comment]
Blender 4.0 support was added in latest commit
