### ISSUE TITLE
Missing Model after GoldSrc .mdl import

### ISSUE THREAD

**Issue by EditaNEmilis** [REDxEYE/SourceIO#246]
Tried to import a Gargantua model from Half-Life using the GoldSrc model importer. Only got the armature rig but no model.

<details><summary><strong>Console Import Log</strong></summary><pre><code>
[INFO]--[GoldSrc::Operators:execute]: Loading 0/1
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'garg_GARG_Pelvis1.bmp'
Traceback (most recent call last):
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\goldsrc_operators.py", line 71, in execute
    import_model(Path(file.name).stem,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\__init__.py", line 20, in import_model
    return import_model_v10(mdl_buffer, mdl_texture_file, scale, parent_collection, disable_collection_sort,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\mdl_v10\import_mdl.py", line 156, in import_model
    remap[model_material_index] = load_material(Path(mdl.header.name).stem, model_texture_info,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\mdl_v10\import_mdl.py", line 189, in load_material
    bpy_material.create_nodes(material_name, model_name=model_name)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\goldsrc_shaders\goldsrc_shader.py", line 39, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
</code></pre></details>

![Image Proof, I guess](https://i.imgur.com/HCrLmUv.png)

**Comment by REDxEYE** [comment]
Blender 4.0 is not supported

**Comment by Cianez** [comment]
> Blender 4.0 is not supported

Downgraded to 3.4 and it's working now. Thanks.
![immagine](https://github.com/REDxEYE/SourceIO/assets/46445923/898b9bd0-af93-4cc9-9a90-936493224d3c)
Hope you add 4.0 support in the future. 👍
