### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by TekuSP** [REDxEYE/SourceIO#25]
![image](https://user-images.githubusercontent.com/13198444/71616485-c0635900-2bb6-11ea-9e8d-a0b0b74d4c5f.png)

[system-info.txt](https://github.com/REDxEYE/SourceIO/files/4012281/system-info.txt)

Blender 2.8.1, Import fails, does not even start...

Version from commit ea4289a

**Comment by REDxEYE** [comment]
Use latest pre-release build or 3.5.5

**Comment by TekuSP** [comment]
I was unable to install 3.5.5.

**Comment by REDxEYE** [comment]
Any errors in console?

**Comment by TekuSP** [comment]
It was writing Importing () modules from file...

But manually copying zip contents into %appdata%\Blender Foundation\Blender\2.81\scripts\addons looks like it imported succesfully. I will try if it crashes with this version too

**Comment by TekuSP** [comment]
No same error on 3.5.5.

```
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\__init__.py", line 70, in execute
    import_textures=self.import_textures
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\mdl\mdl2model.py", line 42, in __init__
    working_directory if working_directory is not None else resolve_root_directory_from_file(path))
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\utilities\path_utilities.py", line 38, in resolve_root_directory_from_file
    return resolve_root_directory_from_file(path.parent)
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\utilities\path_utilities.py", line 38, in resolve_root_directory_from_file
    return resolve_root_directory_from_file(path.parent)
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\utilities\path_utilities.py", line 38, in resolve_root_directory_from_file
    return resolve_root_directory_from_file(path.parent)
  [Previous line repeated 987 more times]
  File "C:\Users\richa\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\SourceIO\utilities\path_utilities.py", line 34, in resolve_root_directory_from_file
    path = Path(path)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\pathlib.py", line 1010, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\pathlib.py", line 665, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\pathlib.py", line 658, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\pathlib.py", line 68, in parse_parts
    it = reversed(parts)
RecursionError: maximum recursion depth exceeded while calling a Python object

location: <unknown location>:-1

```

**Comment by REDxEYE** [comment]
Try latest release then. I never got this error honestly

**Comment by TekuSP** [comment]
Are there any required libraries? Or anything what I could be missing?

**Comment by REDxEYE** [comment]
No, this is just infinite function call loop

**Comment by TekuSP** [comment]
3.5.8 does this:
`Modules Installed () from 'C:\\Users\\richa\\Downloads\\SourceIO-3.5.8.zip' into 'C:\\Users\\richa\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'`

**Comment by REDxEYE** [comment]
Remove -3.5.8 from folder name

**Comment by TekuSP** [comment]
Did not help.

**Comment by REDxEYE** [comment]
Weird, addon does not appear in addon list in blender?

**Comment by TekuSP** [comment]
Nope. Even after manually copying it. 3.5.5 does appear, latest commit does too, but 3.5.8 does not.

**Comment by TekuSP** [comment]
And to make you even more confused, this is clear blender installation, I installed one hour back.

**Comment by REDxEYE** [comment]
Any errors in console on blender startup?

**Comment by TekuSP** [comment]
Nope
![image](https://user-images.githubusercontent.com/13198444/71617094-b3943480-2bb9-11ea-89c7-a8a83c53e0c6.png)

**Comment by REDxEYE** [comment]
Looks like blender just dont see plugin folder. What is name of plugin folder? "SourceIO" or "SourceIO-x.x.x"?

**Comment by TekuSP** [comment]
![image](https://user-images.githubusercontent.com/13198444/71617126-ef2efe80-2bb9-11ea-9f50-bc6115e27a66.png)

**Comment by REDxEYE** [comment]
Now i'm really confused.
Try this one, i just zipped up version i have installed
[SourceIO.zip](https://github.com/REDxEYE/SourceIO/files/4012339/SourceIO.zip)

**Comment by TekuSP** [comment]
![image](https://user-images.githubusercontent.com/13198444/71617253-8dbb5f80-2bba-11ea-93f7-c1ede7fe6309.png)
This is how looks latest commit.

**Comment by TekuSP** [comment]
I will try your version

**Comment by TekuSP** [comment]
Okay, your version installed without problems.

**Comment by TekuSP** [comment]
And it imported without any error.
