### ISSUE TITLE
Materials in .bsp map do not load

### ISSUE THREAD

**Issue by doonv** [REDxEYE/SourceIO#255]
I tried importing `ctf_2fort` from team fortress 2 but i got this error:

```
Python: Traceback (most recent call last):
  File "/home/doonv/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source1/bsp/entities/abstract_entity_handlers.py", line 110, in handle_entity
    handler_function(entity_object, entity_data)
  File "/home/doonv/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source1/bsp/entities/base_entity_handler.py", line 745, in handle_infodecal
    mat.create_material()
  File "/home/doonv/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/material_loader/material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "/home/doonv/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/material_loader/shaders/source1_shaders/lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```

This works perfectly fine for characters (heavy weapons guy and medic works perfectly), but not maps.

**Comment by REDxEYE** [comment]
Blender 4.0 is only supported in  dev version of sourceio

**Comment by doonv** [comment]
oh
