### ISSUE TITLE
imported .BSP map gets corrupted when exporting scene to .GLTF/.GLB

### ISSUE THREAD

**Issue by Sectonidse** [REDxEYE/SourceIO#257]
Before exporting:
![Normal looking d1_cananls_10](https://github.com/REDxEYE/SourceIO/assets/94748461/4ab67684-c7d9-4c0b-b729-cb39aaa0bcda)

After exporting:
![Broken mess](https://github.com/REDxEYE/SourceIO/assets/94748461/31645100-c6ba-44ae-aa28-8d400e7e0819)

The error that appears when importing .BSP file (might be not relatable to this bug):

```
Python: Traceback (most recent call last):
  File "/home/borus/.config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source1/bsp/entities/abstract_entity_handlers.py", line 110, in handle_entity
    handler_function(entity_object, entity_data)
  File "/home/borus/.config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source1/bsp/entities/base_entity_handler.py", line 745, in handle_infodecal
    mat.create_material()
  File "/home/borus/.config/blender/4.0/scripts/addons/SourceIO/blender_bindings/material_loader/material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "/home/borus/.config/blender/4.0/scripts/addons/SourceIO/blender_bindings/material_loader/shaders/source1_shaders/lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```

**Comment by REDxEYE** [comment]
Downgrade to 3.6 or use developer version of sourceio. Official 4.0 support will be in next release
