### ISSUE TITLE
Failed .BSP map loading

### ISSUE THREAD

**Issue by EditaNEmilis** [REDxEYE/SourceIO#258]
I tried to import an Source .bsp map of d2_airex_01.bsp _(Which is the 2002 or 2003 Half-Life 2 beta map)_
And failed to import pretty fast, which I got this console log.

<pre>[INFO]--[d2_airex_01.bsp:__init__]: Loading map "C:\Program Files (x86)\Half-Life 2 2002 Edition\data\02ed\maps\d2_airex_01.bsp"
Traceback (most recent call last):
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 128, in execute
    bsp_map = BSP(self.filepath, content_manager, self)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\blender_bindings\source1\bsp\import_bsp.py", line 78, in __init__
    self.face_lump: Optional[FaceLump] = self.map_file.get_lump('LUMP_FACES')
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\library\source1\bsp\bsp_file.py", line 93, in get_lump
    parsed_lump = self.parse_lump(sub, dep.lump_id, dep.lump_name)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\library\source1\bsp\bsp_file.py", line 128, in parse_lump
    parsed_lump = lump_class(lump_info).parse(buffer, self)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\library\source1\bsp\lumps\face_lump.py", line 18, in parse
    self.faces.append(Face.from_buffer(buffer, self.version, bsp))
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\library\source1\bsp\datatypes\face.py", line 38, in from_buffer
    lightmap_texture_size_in_luxels = buffer.read_fmt("2i")
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO-master\library\utils\file_utils.py", line 229, in read_fmt
    data = struct.unpack_from(self._endian + fmt, self._buffer, self._offset)
struct.error: unpack_from requires a buffer of at least 942412 bytes for unpacking 8 bytes at offset 942404 (actual buffer size is 942408)
<pre>

**Comment by REDxEYE** [comment]
These old version are not yet supported

**Comment by EditaNEmilis** [comment]
Oof, rightt.

**Comment by REDxEYE** [comment]
But if you upload some samples i may try to add support

**Comment by EditaNEmilis** [comment]
Yeah sure, I got some.

https://we.tl/t-cvO763FY1J

**Comment by REDxEYE** [comment]
Vindictus was supported, but due to it's frequent updates and unavailability for me to install and test support for it was broken

**Comment by REDxEYE** [comment]
Solved by adding ability to override steam app id
