### ISSUE TITLE
source 1 maps import with [almost] all textures missing

### ISSUE THREAD

**Issue by staticanimal** [REDxEYE/SourceIO#259]
sourceio version: 4.1.0
blender version: 4.0.2

maps tested from sfm, gmod and hl2 ep2

the error that gets printed to the log:
```
Python: Traceback (most recent call last):
  File "C:\Users\staticanimal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 141, in execute
    bsp_map.load_materials(self.use_bvlg)
  File "C:\Users\staticanimal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 185, in load_materials
    mat.create_material()
  File "C:\Users\staticanimal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "C:\Users\staticanimal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\source1_shaders\lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```

**Comment by REDxEYE** [comment]
SoutceIO currently does not support blender 4.0

**Comment by REDxEYE** [comment]
unreleased version (master branch) support 4.0, but i havent tested it much
