### ISSUE TITLE
Error when trying to uninstall addon

### ISSUE THREAD

**Issue by 4rtb** [REDxEYE/SourceIO#262]
When trying to delete an addon, an error appears (blender 3.6.9, installed version 5.2.0): Error: Python: Traceback (most recent call last):
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\scripts\startup\bl_operators\userpref.py", line 785, in execute
    shutil.rmtree(path)
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\tewald\Desktop\blender-3.6.9-windows-x64\3.6\python\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] ╨Ю╤В╨║╨░╨╖╨░╨╜╨╛ ╨▓ ╨┤╨╛╤Б╤В╤Г╨┐╨╡: 'C:\\Users\\tewald\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\SourceIO-master\\library\\utils\\pylib\\win\\pylib.dll' (blender 3.6.9)

![Screenshot_1](https://github.com/REDxEYE/SourceIO/assets/141040913/d64e18c7-1f7c-44cd-b3df-b6fbcae86422)

[25.02.2024 11_06.webm](https://github.com/REDxEYE/SourceIO/assets/141040913/79c57c39-9928-455a-bdc8-f35635ff0431)

**Comment by REDxEYE** [comment]
Havent found way to fix it
