### ISSUE TITLE
Textures dont load in blender 4.0 with latest 5.2.0 addon version (not master one)

### ISSUE THREAD

**Issue by 4rtb** [REDxEYE/SourceIO#263]
Blender version: 4.0
Addon version: 5.2.0 (latest, not master)

Screenshot
![Безымянный](https://github.com/REDxEYE/SourceIO/assets/141040913/426dcc44-e583-4836-90df-694457a5a009)

Video: 
[26.02.2024 08_06.webm](https://github.com/REDxEYE/SourceIO/assets/141040913/e6be57c3-08da-4a34-b6e5-4c555d8c7927)

Logs:
Traceback (most recent call last):
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 134, in execute
    bsp_map.load_entities()
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 123, in load_entities
    entity_handler.load_entities(self.settings)
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 96, in load_entities
    if not self.handle_entity(entity_data):
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 110, in handle_entity
    handler_function(entity_object, entity_data)
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\base_entity_handler.py", line 745, in handle_infodecal
    mat.create_material()
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\source1_shaders\lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

**Comment by REDxEYE** [comment]
SourceIO 5.2.0 does not support blender 4.0
