### ISSUE TITLE
Specific, Unnamed but providable MDL's refuse to be imported

### ISSUE THREAD

**Issue by Ma110w** [REDxEYE/SourceIO#265]
Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 53, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 31, in import_model_from_full_path
    mdl_file = FileBuffer(mdl_path)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\library\utils\file_utils.py", line 310, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
FileNotFoundError: [Errno 2] No such file or directory: WindowsPath('S:/Topfolder/down1/models/down3/medium/down5/medium/aobjectmdl.mdl')

**Comment by REDxEYE** [comment]
Please provide more context. Console logs for example

**Comment by Ma110w** [comment]
What I'm asking about Isn't a issue that pertains to console logs, I can provide a couple of the MDL's for you too try

**Comment by REDxEYE** [comment]
Ok, drop some models
And mention what game are they coming from

**Comment by Ma110w** [comment]
Titanfall 2, The Eden Map from Multiplayer, its on [google drive](https://drive.google.com/file/d/1ZvUP-dm6jUWCE9EIvjsWfTKZyy8WR-JG/view?usp=sharing) https://drive.google.com/file/d/1ZvUP-dm6jUWCE9EIvjsWfTKZyy8WR-JG/view?usp=sharing

**Comment by REDxEYE** [comment]
Titanfall2 not fully supported

**Comment by Ma110w** [comment]
not fully is a overstatement, more like not at all.
