### ISSUE TITLE
Problem with texture loading while opening a TF2 BSP Map file

### ISSUE THREAD

**Issue by Ranily57** [REDxEYE/SourceIO#266]
![image](https://github.com/REDxEYE/SourceIO/assets/62222362/ac52797a-fa4d-4b36-b56e-b96ada1255fd)

This is ctf_2fort.bsp, and some part of the map is mission and no texture at all.

*Missing part*
![image](https://github.com/REDxEYE/SourceIO/assets/62222362/c043edc6-d379-4671-b20d-9b3f5787330a)

```py
Python: Traceback (most recent call last):
  File "C:\Users\raphi\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 110, in handle_entity
    handler_function(entity_object, entity_data)
  File "C:\Users\raphi\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\base_entity_handler.py", line 745, in handle_infodecal
    mat.create_material()
  File "C:\Users\raphi\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 44, in create_material
    handler.create_nodes(self.material_name)
  File "C:\Users\raphi\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\source1_shaders\lightmap_generic.py", line 91, in create_nodes
    shader.inputs['Specular'].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

```

**Comment by REDxEYE** [comment]
SourceIO 5.2.0 does not work in Blender 4.X

**Comment by REDxEYE** [comment]
Use master
