### ISSUE TITLE
error on importing script rig

### ISSUE THREAD

**Issue by BreadedGobber** [REDxEYE/SourceIO#273]
the error code i keep getting 

```
**Python: Traceback (most recent call last):
  File "C:\Users\ahjan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 87, in execute
    load_script(directory)
  File "C:\Users\ahjan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\fake_sfm\__init__.py", line 69, in load_script
    exec(compiled, {'sfm': sfm.SFM(), 'sfmUtils': sfm_utils.SfmUtils(), 'print': sfm.sfm.sfm_logger.print})
  File "C:\Users\ahjan\OneDrive\Desktop\usermod\scripts\sfm\animset\rig_femboy_pyro.py", line 838, in <module>
    BuildRig(4,True,True,boneList,'x',False,None);
  File "C:\Users\ahjan\OneDrive\Desktop\usermod\scripts\sfm\animset\rig_femboy_pyro.py", line 265, in BuildRig
    animSet = sfm.GetCurrentAnimationSet()
  File "C:\Users\ahjan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\fake_sfm\sfm\__init__.py", line 285, in GetCurrentAnimationSet
    assert obj.type == 'ARMATURE'
AttributeError: 'NoneType' object has no attribute 'type'**

```

any fixes or anything else ?

**Comment by REDxEYE** [comment]
No fixes any time soon. It never fully worked
