### ISSUE TITLE
The Add-on doesnt can activate

### ISSUE THREAD

**Issue by Kubyszynsiuu** [REDxEYE/SourceIO#285]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\__init__.py", line 26, in <module>
    from SourceIO.blender_bindings.bindings import register, unregister
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\bindings.py", line 9, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\flex_operators.py", line 5, in <module>
    from .shared_operators import UITools
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\shared_operators.py", line 12, in <module>
    from .import_settings_base import ModelOptions
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\import_settings_base.py", line 4, in <module>
    from ...library.utils.math_utilities import SOURCE1_HAMMER_UNIT_TO_METERS
ModuleNotFoundError: No module named 'SourceIO.library.utils'

**Comment by REDxEYE** [comment]
Make sure you're either running latest version or in-dev version

**Comment by Kubyszynsiuu** [comment]
> Make sure you're either running latest version or in-dev version

I already did it

**Comment by REDxEYE** [comment]
Try to install 5.3.0 release, but before installing make sure to delete old version(s)
