### ISSUE TITLE
can't (re)install or remove addon

### ISSUE THREAD

**Issue by MrMage750** [REDxEYE/SourceIO#291]
trying to install the latest version for possible 4.0 support, but trying to remove the old addon or installing the new one results in this error

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Owner\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\SourceIO-master\\library\\utils\\pylib\\win\\pylib.dll'

there's also no sourceIO folder nor file for me to delete in my addons directory

**Comment by MrMage750** [comment]
restarting blender resolved both my problems
