### ISSUE TITLE
Can't load entities

### ISSUE THREAD

**Issue by MrKoix** [REDxEYE/SourceIO#294]
Error: Python: Traceback (most recent call last):
  File "C:\Users\B┼éa┼╝ej\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\shared_operators.py", line 107, in execute
    container = load_model(model_resource, custom_prop_data["scale"], lod_mask=1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\B┼éa┼╝ej\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 78, in load_model
    objects = create_meshes(resource, ContentManager(), container, scale, lod_mask, import_attachments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\B┼éa┼╝ej\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 168, in create_meshes
    sub_meshes = load_internal_mesh(model_resource, cm, container, scale, mesh_info, import_attachments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\B┼éa┼╝ej\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 193, in load_internal_mesh
    return create_mesh(model_resource, cm, container, data_block, vbib_block, morph_block, scale, mesh_index,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\B┼éa┼╝ej\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 408, in create_mesh
    mesh.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'

**Comment by REDxEYE** [comment]
For Blender 4.1 please use https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip
