### ISSUE TITLE
Add-on Not Activating for Blender 4.1 (Mac)

### ISSUE THREAD

**Issue by RedArrow22** [REDxEYE/SourceIO#296]
I just updated Blender and no SourceIO is not behaving with me to activate. IDK what could be the cause.

Any ideas? I need a response on this as soon as possible as I have a collab to work on which is nearly due in a month.

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/__init__.py", line 26, in <module>
    from SourceIO.blender_bindings.bindings import register, unregister
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/bindings.py", line 9, in <module>
    from .operators.flex_operators import SourceIO_PG_FlexController
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/operators/flex_operators.py", line 5, in <module>
    from .shared_operators import UITools
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/operators/shared_operators.py", line 13, in <module>
    from ..models import import_model
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/models/__init__.py", line 4, in <module>
    from SourceIO.blender_bindings.models.model_tags import HANDLERS, choose_model_importer
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/models/model_tags.py", line 6, in <module>
    from SourceIO.blender_bindings.shared.model_container import ModelContainer
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/blender_bindings/shared/model_container.py", line 9, in <module>
    from ...library.models.mdl.v36.mdl_file import MdlV36 as S1MdlV36
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/library/models/mdl/v36/__init__.py", line 1, in <module>
    from .mdl_file import MdlV36
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/library/models/mdl/v36/mdl_file.py", line 13, in <module>
    from ..v49.flex_expressions import *
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/library/models/mdl/v49/__init__.py", line 1, in <module>
    from .mdl_file import MdlV49
  File "/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/library/models/mdl/v49/mdl_file.py", line 8, in <module>
    from SourceIO.logger import SourceLogMan
ImportError: cannot import name 'SourceLogMan' from 'SourceIO.logger' (/Users/Red_Arrow22/Library/Application Support/Blender/4.1/scripts/addons/SourceIO/logger.py)

**Comment by REDxEYE** [comment]
Try installing this version https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by RedArrow22** [comment]
IT WORKS!!! Thanks a lot for the help! This saved me so much trouble! ♥️
