### ISSUE TITLE
Blender 4.1+ can't import any Source 2 .vmdl_c

### ISSUE THREAD

**Issue by twenty41** [REDxEYE/SourceIO#297]
Getting this error every time

Installed, restarted, tried again

```
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_audio_new_sound') provider for audio_new_sound
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_custom_character') provider for custom_character
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_hdri') provider for hdri
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_hl2hd') provider for hl2hd
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_hlvrcfg') provider for hlvr_addons
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_metro') provider for metro
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_particles_alyx') provider for particles_alyx
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_polyhaven') provider for polyhaven
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_portal') provider for portal
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_rdr2') provider for rdr2
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_sbmp') provider for sbmp
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_sourcefilmmaker') provider for sourcefilmmaker
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_stalker') provider for stalker
[INFO]--[ContentManager:register_content_provider]: Registered HLAAddonProvider('hla_addon_tdmcars') provider for tdmcars
[INFO]--[ContentManager:register_content_provider]: Registered Gameinfo2ContentProvider('hlvr') provider for hlvr
[INFO]--[ContentManager:register_content_provider]: Registered VPKContentProvider('hlvr_pak01_dir') provider for hlvr
[INFO]--[ContentManager:register_content_provider]: Registered VPKContentProvider('hlvr_shaders_pc_dir') provider for hlvr
[INFO]--[ContentManager:register_content_provider]: Registered VPKContentProvider('hlvr_shaders_vulkan_dir') provider for hlvr
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('hlvr_addons') provider for hlvr_addons
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('hl2hd') provider for hl2hd
Loading 1/1
[INFO]--[ContentManager:find_file]: Requesting models\themask\scenebuildthemes\rocks\bigrocks1_sg_bg_body_lod0.vmesh_c file
[DEBUG]--[ContentManager:find_file]: Found in hla_addon_sbmp!
Decoding vertex block 2304/2355
{'m_nPrimitiveType': 'RENDER_PRIM_TRIANGLES', 'm_nBaseVertex': 0, 'm_nVertexCount': 2355, 'm_nStartIndex': 0, 'm_nIndexCount': 10017, 'm_nStartInstance': 0, 'm_nInstanceCount': 0, 'm_flUvDensity': 228.77749633789062, 'm_vTintColor': array([1., 1., 1.]), 'm_CullDataIndex': -1, 'm_indexBuffer': {'m_hBuffer': 0, 'm_nBindOffsetBytes': 0}, 'm_material': 'materials/themask/scenebuildthemes/rocks/rocks_group_6v_c.vmat', 'm_vertexBuffers': [{'m_hBuffer': 0, 'm_nBindOffsetBytes': 0}], 'm_bUseCompressedNormalTangent': 1}
[INFO]--[ContentManager:find_file]: Requesting materials\themask\scenebuildthemes\rocks\rocks_group_6v_c.vmat_c file
[DEBUG]--[ContentManager:find_file]: Found in hla_addon_sbmp!
[INFO]--[Shaders::vr_complex.vfx:create_nodes]: Creating material 'rocks_group_6v_c'
Loading texture materials/themask/scenebuildthemes/rocks/rocks_group_6v_c_color_tga_a83425f4.vtex
[INFO]--[ContentManager:find_file]: Requesting materials\themask\scenebuildthemes\rocks\rocks_group_6v_c_color_tga_a83425f4.vtex_c file
[DEBUG]--[ContentManager:find_file]: Found in hla_addon_sbmp!
[INFO]--[Source2::Texture:import_texture]: Loading materials\themask\scenebuildthemes\rocks\rocks_group_6v_c_color_tga_a83425f4.vtex texture
[INFO]--[TextureUtils:create_and_cache_texture]: Save 'materials/themask/scenebuildthemes/rocks/rocks_group_6v_c_color_tga_a83425f4.vtex' texture to memory
Loading texture materials/themask/scenebuildthemes/rocks/rocks_group_6v_c_normal_tga_3ca11408.vtex
[INFO]--[ContentManager:find_file]: Requesting materials\themask\scenebuildthemes\rocks\rocks_group_6v_c_normal_tga_3ca11408.vtex_c file
[DEBUG]--[ContentManager:find_file]: Found in hla_addon_sbmp!
[INFO]--[Source2::Texture:import_texture]: Loading materials\themask\scenebuildthemes\rocks\rocks_group_6v_c_normal_tga_3ca11408.vtex texture
[INFO]--[TextureUtils:create_and_cache_texture]: Save 'materials/themask/scenebuildthemes/rocks/rocks_group_6v_c_normal_tga_3ca11408.vtex' texture to memory
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 60, in execute
    container = load_model(model_resource, self.scale, self.lod_mask,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 78, in load_model
    objects = create_meshes(resource, ContentManager(), container, scale, lod_mask, import_attachments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 172, in create_meshes
    sub_meshes = load_external_mesh(model_resource, cm, container, scale, i, mesh_resource, import_attachments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 211, in load_external_mesh
    return create_mesh(model_resource, cm, container, data_block, vbib_block, morph_block, scale, mesh_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 408, in create_mesh
    mesh.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
```

**Comment by REDxEYE** [comment]
Use [this ](https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip) version for blender 4.0+
