### ISSUE TITLE
Consistent script crash for importing HL:A Models, Maps.

### ISSUE THREAD

**Issue by OverwatchVoice** [REDxEYE/SourceIO#298]
Title, pretty much.
Python locks up when it tries to load maps or materials. Traceback below. Material assets seem to work just fine.

_Maps_
`Python: Traceback (most recent call last):
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 145, in execute
    load_map(model, ContentManager(), self.scale)
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vwrld\loader.py", line 36, in load_map
    world_resource_path = next(filter(lambda a: a.endswith(".vwrld"), manifest_resource.get_child_resources()), None)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vwrld\loader.py", line 36, in <lambda>
    world_resource_path = next(filter(lambda a: a.endswith(".vwrld"), manifest_resource.get_child_resources()), None)
                                                ^^^^^^^^^^
AttributeError: 'int' object has no attribute 'endswith'
`

_Models_
`Python: Traceback (most recent call last):
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 60, in execute
    container = load_model(model_resource, self.scale, self.lod_mask,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 78, in load_model
    objects = create_meshes(resource, ContentManager(), container, scale, lod_mask, import_attachments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 168, in create_meshes
    sub_meshes = load_internal_mesh(model_resource, cm, container, scale, mesh_info, import_attachments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 193, in load_internal_mesh
    return create_mesh(model_resource, cm, container, data_block, vbib_block, morph_block, scale, mesh_index,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 408, in create_mesh
    mesh.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
`

**Comment by REDxEYE** [comment]
Try with this version of SourceIO https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by OverwatchVoice** [comment]
Tested loading a map, locked up
`Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'SourceIO.library.source2.data_types.blocks.agrp_block'
`

Tested loading a model, locked up
`Python: Traceback (most recent call last):
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\source2_operators.py", line 60, in execute
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 70, in load_model
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source2\vmdl_loader.py", line 94, in create_armature
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\library\source2\resource_types\compiled_model_resource.py", line 16, in get_bones
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 53, in get_data_block
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 38, in get_data_block
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\library\source2\resource_types\resource.py", line 65, in _get_block_class
  File "C:\Users\pavla\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\library\source2\data_types\blocks\all_blocks.py", line 7, in get_block_class
ModuleNotFoundError: No module named 'SourceIO.library.source2.data_types.blocks.agrp_block'
`

**Comment by REDxEYE** [comment]
I don't have such a problem on my side. Try removing all old addon files and reinstalling

**Comment by OverwatchVoice** [comment]
Will do, thanks for the quick response. I'll get back to you soon

**Comment by OverwatchVoice** [comment]
Did a reinstall and turned off any other addons. Seems to be working fine now!
