### ISSUE TITLE
List index out of range error when importing a cube in vmdl_c format

### ISSUE THREAD

**Issue by xyZ54** [REDxEYE/SourceIO#30]
It managed to import a skeleton but not the mesh

Traceback (most recent call last):
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\__init__.py", line 118, in execute
    Vmdl(str(directory / file.name), True)
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\source2\vmdl.py", line 48, in __init__
    self.build_meshes(self.main_collection, armature)
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\source2\vmdl.py", line 51, in build_meshes
    control_block = self.valve_file.get_data_block(block_name="CTRL")[0]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
model file example please

**Comment by xyZ54** [comment]
https://drive.google.com/open?id=1XNRPamlbmns525XE7g0XO-mLbOhsFVM0

**Comment by REDxEYE** [comment]
Latest commit should fix it

**Comment by xyZ54** [comment]
Now there is this

Traceback (most recent call last):
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\__init__.py", line 149, in execute
    model.load_mesh(self.invert_uv)
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\source2\resouce_types\valve_model.py", line 56, in load_mesh
    self.build_meshes(main_collection, armature, invert_uv)
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\source2\resouce_types\valve_model.py", line 84, in build_meshes
    invert_uv, mesh_index)
  File "C:\Users\A5\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SourceIO\source2\resouce_types\valve_model.py", line 171, in build_mesh
    need_to_convert_normals = type(used_vertices[0].normal[0]) is int
IndexError: list index out of range
