### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MelonHell** [REDxEYE/SourceIO#302]
## Steps to reproduce:
- File -> Import -> Source Engine Assets -> Source Map (.bsp)
- Select this map:
[gd_rialto.zip](https://github.com/user-attachments/files/15777880/gd_rialto.zip) (Steam link: https://steamcommunity.com/sharedfiles/filedetails/?id=2307675806)
- Get this exception:
```
Traceback (most recent call last):
  File "D:\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 96, in execute
    import_bsp(Path(self.filepath), f, content_manager, self,
  File "D:\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 57, in import_bsp
    import_static_props(bsp, settings, master_collection, logger)
  File "D:\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 131, in import_static_props
    model_name = static_prop_lump.model_names[prop.prop_type]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

## Other:

I was able to load the map by replacing this line
https://github.com/REDxEYE/SourceIO/blob/c6809932a31d7ca01816dc9aa1b30e9b07fd82fb/blender_bindings/source1/bsp/import_bsp.py#L131
with this:
```py
                try:
                    model_name = static_prop_lump.model_names[prop.prop_type]
                except Exception as e:
                    continue
```

**Comment by REDxEYE** [comment]
Make sure to set steam app id override to CSGO, otherwise, sourceio have no idea what version of BSP it is

**Comment by MelonHell** [comment]
This seems to solve the problem. I feel stupid
