### ISSUE TITLE
"IndexError: list index out of range" error when importing custom maps

### ISSUE THREAD

**Issue by LightShade12** [REDxEYE/SourceIO#303]
Blender version: 4.0 release
Platform: Windows 10
SourceIO version: 5.4.0

Issue: When attempting to import custom goldsrc maps for cstrike 1.6, I get an error and the import fails.

Expectation: I hoped the map would load normally like other official maps

The log while importing de_dust_2_2020:
```
Traceback (most recent call last):
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\goldsrc_operators.py", line 47, in execute
    bsp.load_map()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 106, in load_map
    self.load_entities()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 241, in load_entities
    entity_handlers[entity_class](entity, self.scale, self.bsp_collection, self.fix_rotation,
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\entity_handlers.py", line 18, in handle_generic_model_prop
    return handle_model_prop(model_name, entity_data, scale, parent_collection,
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\entity_handlers.py", line 56, in handle_model_prop
    model_container = import_model(model_name, mdl_buffer, content_manager, opts, None)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\models\__init__.py", line 29, in import_model
    container = handler(model_path, buffer, content_manager, options)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\models\mdl10\__init__.py", line 17, in import_mdl10
    return import_model(buffer, texture_mdl, options)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\models\mdl10\import_mdl.py", line 129, in import_model
    process(mesh_triverts[0],
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\models\mdl10\import_mdl.py", line 116, in process
    transform = bone_transforms[body_part_model.bone_normal_info[v0.vertex_index]].to_3x3()
IndexError: list index out of range
```
more log:
![image](https://github.com/REDxEYE/SourceIO/assets/102753608/0335d95b-15cb-4b43-bf53-76258bd05c45)
only half of the models get imported:
![image](https://github.com/REDxEYE/SourceIO/assets/102753608/1ac7a567-becc-4281-9a97-7588f4cc3319)
Import settings:
![image](https://github.com/REDxEYE/SourceIO/assets/102753608/21c1f649-d925-4055-b1ae-b679c36cbe27)

**Comment by REDxEYE** [comment]
Fixed now

**Comment by LightShade12** [comment]
Thank you for such rapid response. However now there's a new error: ```TypeError: expected sequence size 8192, got 262144```
here's the log:
```
[ERROR]--[GoldSrc::Texture:get_contents]: Could not find texture resource: !C2A54
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material '!C2A54'
[INFO]--[Shaders::goldsrc_shader_mode2:create_nodes]: Creating material '!C2A54_RM2'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'SCROLLDUST2020'
[INFO]--[Shaders::goldsrc_shader_mode5:create_nodes]: Creating material 'SCROLLDUST2020_RM5'
[INFO]--[ContentManager:find_file]: Requesting +0WATERFALL1 file
[ERROR]--[GoldSrc::Texture:get_contents]: Could not find texture resource: +0WATERFALL1
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material '+0WATERFALL1'
[INFO]--[Shaders::goldsrc_shader_mode2:create_nodes]: Creating material '+0WATERFALL1_RM2'
[INFO]--[ContentManager:find_file]: Requesting REDHANGINGRUG file
[DEBUG]--[ContentManager:find_file]: Found in cstrike_itsitaly!
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'REDHANGINGRUG'
Traceback (most recent call last):
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\goldsrc_operators.py", line 47, in execute
    bsp.load_map()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 106, in load_map
    self.load_entities()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 262, in load_entities
    self.load_brush(entity_class, entity, "brushes")
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 342, in load_brush
    model_object = self.load_bmodel(model_index,
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 173, in load_bmodel
    self.load_material(face_texture_name)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 133, in load_material
    shader.create_nodes(mat, rad_data)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\goldsrc_shaders\goldsrc_shader.py", line 16, in create_nodes
    basetexture = self.load_texture(material.name, model_name)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\goldsrc_shader_base.py", line 46, in load_texture
    model_texture.pixels.foreach_set(model_texture_info.data.ravel())
TypeError: expected sequence size 8192, got 262144
```
here's a longer log:
![image](https://github.com/REDxEYE/SourceIO/assets/102753608/d53c29c9-bb50-4391-b40c-40585bad856e)
This is for the same de_dust_2020 map import.

**Comment by REDxEYE** [comment]
Please upload map and it's resources

**Comment by LightShade12** [comment]
Here is the map source:
https://gamebanana.com/dl/546696

**Comment by REDxEYE** [comment]
Re-tested it with 5.4.1 and havent got any errors. Please retry with 5.4.1

**Comment by REDxEYE** [comment]
Have you tested it with latest release?

**Comment by LightShade12** [comment]
I do remember installing the latest version last time you mentioned the new release. But I found I was using `5.4.1`.
Now I downloaded `5.4.3` and tried to import `de_dust2_2020.bsp`.
However unfortunately I still only get partial import.
![image](https://github.com/user-attachments/assets/d844536c-033c-45df-b78d-f190673eee4d)
Here's the scenegraph:
![image](https://github.com/user-attachments/assets/d349538f-0666-4b06-af37-52855b4868a4)
here's the full log during importing `de_dust2_2020.bsp`:
```
[INFO]--[GoldSrc::Operators:execute]: Loading 0/1
[INFO]--[de_dust2_2020:__init__]: Loading map "de_dust2_2020"
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcContentProvider('cstrike') provider for cstrike
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcWADContentProvider('cstrike_decals.wad') provider for cstrike
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('platform') provider for platform
[INFO]--[ContentManager:find_file]: Requesting maps\de_dust2_2020.rad file
[INFO]--[ContentManager:find_file]: Requesting maps\lights.rad file
[DEBUG]--[de_dust2_2020:__init__]: Rad data: {}
[INFO]--[ContentManager:find_path]: Requesting None file
[INFO]--[ContentManager:find_path]: Requesting None file
[INFO]--[ContentManager:find_path]: Requesting D:\programs\Games\Counter-Strike\cstrike\cs_havana.wad file
[DEBUG]--[ContentManager:find_path]: Found in cstrike!
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcWADContentProvider('cstrike_cs_havana') provider for cstrike
[INFO]--[ContentManager:find_path]: Requesting D:\programs\Games\Counter-Strike\cstrike\de_piranesi.wad file
[DEBUG]--[ContentManager:find_path]: Found in cstrike!
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcWADContentProvider('cstrike_de_piranesi') provider for cstrike
[INFO]--[ContentManager:find_path]: Requesting D:\programs\Games\Counter-Strike\cstrike\itsitaly.wad file
[DEBUG]--[ContentManager:find_path]: Found in cstrike!
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcWADContentProvider('cstrike_itsitaly') provider for cstrike
[INFO]--[ContentManager:find_path]: Requesting D:\programs\Games\Counter-Strike\cstrike\torntextures.wad file
[DEBUG]--[ContentManager:find_path]: Found in cstrike!
[INFO]--[ContentManager:register_content_provider]: Registered GoldSrcWADContentProvider('cstrike_torntextures') provider for cstrike
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE4SB'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE4T'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE4S'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE2SB'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE2TB'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRTE2SC'
[WARNING]--[de_dust2_2020:load_trigger]: Trigger "trigger_camera" does not reference any models
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'info_target': {'origin': '-1520 1264 40', 'angles': '0 0 0', 'targetname': 'cam1t', 'classname': 'info_target'}
[WARNING]--[de_dust2_2020:load_trigger]: Trigger "trigger_camera" does not reference any models
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'info_target': {'origin': '1160 1040 144', 'angles': '0 0 0', 'targetname': 'cam2t', 'classname': 'info_target'}
[WARNING]--[de_dust2_2020:load_trigger]: Trigger "trigger_camera" does not reference any models
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'info_target': {'origin': '-560 608 -32', 'angles': '0 0 0', 'targetname': 'cam3t', 'classname': 'info_target'}
[INFO]--[ContentManager:find_file]: Requesting models\chick.mdl file
[DEBUG]--[ContentManager:find_file]: Found in cstrike!
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:10
[INFO]--[ContentManager:find_file]: Requesting models\chickt.mdl file
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'chick_skin.bmp'
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_shooter': {'origin': '-1456 -1243.96 48', 'spawnflags': '1', 'targetname': 'chicken_kill_1', 'm_iGibs': '10', 'm_flVelocity': '150', 'm_flVariance': '5', 'm_flGibLife': '4', 'rendercolor': '0 0 0', 'shootsounds': '-1', 'shootmodel': 'models/feather.mdl', 'classname': 'env_shooter'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '-1416 -1244 24', 'renderamt': '0', 'targetname': 'chicken_kill_1', 'target': 'chicken_1', 'spawnflags': '13', 'classname': 'env_render'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '-1416 -1244 64', 'targetname': 'chicken_respawn', 'target': 'chicken_1', 'renderamt': '255', 'spawnflags': '13', 'classname': 'env_render'}
[INFO]--[ContentManager:find_file]: Requesting models\chick.mdl file
[DEBUG]--[ContentManager:find_file]: Found in cstrike!
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:10
[INFO]--[ContentManager:find_file]: Requesting models\chickt.mdl file
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_shooter': {'origin': '1200.04 -1056 48', 'spawnflags': '1', 'targetname': 'chicken_kill_2', 'm_iGibs': '10', 'm_flVelocity': '150', 'm_flVariance': '5', 'm_flGibLife': '4', 'rendercolor': '0 0 0', 'shootsounds': '-1', 'shootmodel': 'models/feather.mdl', 'classname': 'env_shooter'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '1240.04 -1056 24', 'renderamt': '0', 'targetname': 'chicken_kill_2', 'target': 'chicken_2', 'spawnflags': '13', 'classname': 'env_render'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '1240.04 -1056 64', 'targetname': 'chicken_respawn', 'target': 'chicken_2', 'renderamt': '255', 'spawnflags': '13', 'classname': 'env_render'}
[INFO]--[ContentManager:find_file]: Requesting models\chick.mdl file
[DEBUG]--[ContentManager:find_file]: Found in cstrike!
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:10
[INFO]--[ContentManager:find_file]: Requesting models\chickt.mdl file
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_shooter': {'origin': '1440 1872.04 176', 'spawnflags': '1', 'targetname': 'chicken_kill_3', 'm_iGibs': '10', 'm_flVelocity': '150', 'm_flVariance': '5', 'm_flGibLife': '4', 'rendercolor': '0 0 0', 'shootsounds': '-1', 'shootmodel': 'models/feather.mdl', 'classname': 'env_shooter'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '1440 1912.04 152', 'renderamt': '0', 'targetname': 'chicken_kill_3', 'target': 'chicken_3', 'spawnflags': '13', 'classname': 'env_render'}
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_render': {'origin': '1440 1912.04 192', 'targetname': 'chicken_respawn', 'target': 'chicken_3', 'renderamt': '255', 'spawnflags': '13', 'classname': 'env_render'}
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRETE6'
[WARNING]--[de_dust2_2020:load_entities]: Skipping unsupported entity 'env_sprite': {'origin': '-1239 -16 -32', 'rendermode': '5', 'renderamt': '255', 'rendercolor': '0 0 0', 'framerate': '10', 'scale': '0.5', 'spawnflags': '0', 'model': 'sprites/de_dust2_2020/flame.spr', 'classname': 'env_sprite'}
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020TRIM6'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020WALL2'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020CRETE'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020TRIM3'
[INFO]--[ContentManager:find_file]: Requesting models\de_dust2_2020\props.mdl file
[DEBUG]--[ContentManager:find_file]: Found in cstrike!
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:10
[INFO]--[ContentManager:find_file]: Requesting models\de_dust2_2020\propst.mdl file
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Pallet.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Panzer.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Grass.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Palm.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Crete.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Pot.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Funkia.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Oil.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Kubba.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Kubba2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Kubba4.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Kubba3.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Chrome.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Torch.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Torch2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Flower.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Flower2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rope.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Car.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Car2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Cactus.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock3.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Flower3.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock10.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock11.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock6.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sand.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock12.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock9.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock8.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sand3.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock7.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sand4.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sand2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock4.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Rock5.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_n0th1ng.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Flower4.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Fireplace.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Logs.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Wagon.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Flower5.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sarcophagus2.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'props_Dust2020Sarcophagus.bmp'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020BRRLS'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020BRRLT'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'DUST2020WOOD'
[INFO]--[ContentManager:find_file]: Requesting OLDRADIO file
[DEBUG]--[ContentManager:find_file]: Found in cstrike_itsitaly!
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'OLDRADIO'
[INFO]--[ContentManager:find_file]: Requesting !C2A54 file
[ERROR]--[GoldSrc::Texture:get_contents]: Could not find texture resource: !C2A54
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material '!C2A54'
[INFO]--[Shaders::goldsrc_shader_mode2:create_nodes]: Creating material '!C2A54_RM2'
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'SCROLLDUST2020'
[INFO]--[Shaders::goldsrc_shader_mode5:create_nodes]: Creating material 'SCROLLDUST2020_RM5'
[INFO]--[ContentManager:find_file]: Requesting +0WATERFALL1 file
[ERROR]--[GoldSrc::Texture:get_contents]: Could not find texture resource: +0WATERFALL1
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material '+0WATERFALL1'
[INFO]--[Shaders::goldsrc_shader_mode2:create_nodes]: Creating material '+0WATERFALL1_RM2'
[INFO]--[ContentManager:find_file]: Requesting REDHANGINGRUG file
[DEBUG]--[ContentManager:find_file]: Found in cstrike_itsitaly!
[INFO]--[Shaders::goldsrc_shader:create_nodes]: Creating material 'REDHANGINGRUG'
Traceback (most recent call last):
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\goldsrc_operators.py", line 47, in execute
    bsp.load_map()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 106, in load_map
    self.load_entities()
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 262, in load_entities
    self.load_brush(entity_class, entity, "brushes")
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 342, in load_brush
    model_object = self.load_bmodel(model_index,
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 173, in load_bmodel
    self.load_material(face_texture_name)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 133, in load_material
    shader.create_nodes(mat, rad_data)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\goldsrc_shaders\goldsrc_shader.py", line 16, in create_nodes
    basetexture = self.load_texture(material.name, model_name)
  File "C:\Users\subha\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\goldsrc_shader_base.py", line 46, in load_texture
    model_texture.pixels.foreach_set(model_texture_info.data.ravel())
TypeError: expected sequence size 8192, got 262144
```

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards
