### ISSUE TITLE
cannot import name 'load_vtf_texturem' from 'SourceIO.library.utils.rustlib.linux_x64.rustlib'

### ISSUE THREAD

**Issue by EntityinArray** [REDxEYE/SourceIO#312]
SourceIO 5.4.3
Blender 4.2
ArchLinux x86_64

Upon installing the addon, this error occurs
```
Python: Traceback (most recent call last):
  File "/home/entityinarray/Downloads/blender-4.2.0-linux-x64/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 1302, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/entityinarray/Downloads/blender-4.2.0-linux-x64/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2338, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "/home/entityinarray/Downloads/blender-4.2.0-linux-x64/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2465, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "/home/entityinarray/Downloads/blender-4.2.0-linux-x64/4.2/scripts/startup/bl_operators/userpref.py", line 780, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "/home/entityinarray/Downloads/blender-4.2.0-linux-x64/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: cannot import name 'load_vtf_texturem' from 'SourceIO.library.utils.rustlib.linux_x64.rustlib' (/home/entityinarray/.config/blender/4.2/scripts/addons/SourceIO/library/utils/rustlib/linux_x64/rustlib.abi3.so)

```

Upon clicking a checkbox to enable SourceIO this error occurs:
```
cannot import name 'load_vtf_texturem' from 'SourceIO.library.utils.rustlib.linux_x64.rustlib' (/home/entityinarray/.config/blender/4.2/scripts/addons/SourceIO/library/utils/rustlib/linux_x64/rustlib.abi3.so)
```

Tried deleting `~/.config` and running Blender, same issue.
Blender 4.2 downloaded from `blender.org` as tar.gz

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/releases/tag/5.4.4

**Comment by EntityinArray** [comment]
Thank you! Will test today's evening
