### ISSUE TITLE
Python error while importing mdl file

### ISSUE THREAD

**Issue by dpetukhov** [REDxEYE/SourceIO#317]
Hi.

I can not import mdl file. It gives me an error:

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 58, in execute
    put_into_collections(model_container, mdl_path.stem, bodygroup_grouping=self.bodygroup_grouping)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SourceIO\blender_bindings\models\common.py", line 50, in put_into_collections
    if model_container.bodygroups:
AttributeError: 'NoneType' object has no attribute 'bodygroups'
```

See mdl file attached. It's from doom3 weapon pack for garrys mod.

[v_chainsaw.zip](https://github.com/user-attachments/files/16766844/v_chainsaw.zip)

**Comment by REDxEYE** [comment]
Your file is malformed, dont use gmad to unpack gma files, use crowbar
