### ISSUE TITLE
PermissionError: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by A12user** [REDxEYE/SourceIO#325]
Platform: Windows Pro (x64)
Blender Version: 4.1
  While trying to install SourceIO, it comes back with a permission denied error, I have tried restarting my computer and blende, I will post the full error, but I will have to censor some of the file paths for my own privacy.
  
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\startup\bl_operators\userpref.py", line 688, in execute
    _module_filesystem_remove(path_addons, f)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\startup\bl_operators\userpref.py", line 52, in _module_filesystem_remove
    shutil.rmtree(f_full)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\#####\\####\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\SourceIO\\library\\utils\\pylib_loader\\win\\pylib.pyd'

**Comment by REDxEYE** [comment]
Disable addon and restart blender. Than it will allow you to delete the addon
