### ISSUE TITLE
Update to python 3.8

### ISSUE THREAD

**Issue by mirh** [REDxEYE/SourceIO#33]
I'm getting this error when trying to load latest version
```
PySourceIOTextureUtils import error
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "../blender/2.82/scripts/addons/SourceIO/__init__.py", line 28, in <module>
    from .source2.resouce_types.vmdl import Vmdl
  File "../blender/2.82/scripts/addons/SourceIO/source2/resouce_types/vmdl.py", line 10, in <module>
    from ..source2 import ValveFile
  File "../blender/2.82/scripts/addons/SourceIO/source2/source2.py", line 10, in <module>
    from .blocks import DataBlock
  File "../blender/2.82/scripts/addons/SourceIO/source2/blocks/__init__.py", line 6, in <module>
    from .texture_data_block import TextureBlock
  File "../blender/2.82/scripts/addons/SourceIO/source2/blocks/texture_data_block.py", line 8, in <module>
    from ..utils.PySourceIOUtils import *
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0].
```

**Comment by REDxEYE** [comment]
Windows Blender use python 3.7 so i provided builds for 3.7.
[PySourceIOTextureUtils.zip](https://github.com/REDxEYE/SourceIO/files/4573975/PySourceIOTextureUtils.zip)
This should be 3.8 build, just replace file

**Comment by mirh** [comment]
Ohh I see, thank you. 
[Looks like](https://developer.blender.org/T68774) this is gonna take another year to improve. 

But where should I put that? I have just PySourceIOUtils.so here.

**Comment by REDxEYE** [comment]
put it into addon folder \scripts\addons\SourceIO\source2\utils\PySourceIOUtils.so

**Comment by mirh** [comment]
Duh, I'm dumb. I hadn't noticed the error message had changed. 
```
PySourceIOTextureUtils import error
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "../blender/2.82/scripts/addons/SourceIO/__init__.py", line 28, in <module>
    from .source2.resouce_types.vmdl import Vmdl
  File "../blender/2.82/scripts/addons/SourceIO/source2/resouce_types/vmdl.py", line 10, in <module>
    from ..source2 import ValveFile
  File "../blender/2.82/scripts/addons/SourceIO/source2/source2.py", line 10, in <module>
    from .blocks import DataBlock
  File "../blender/2.82/scripts/addons/SourceIO/source2/blocks/__init__.py", line 6, in <module>
    from .texture_data_block import TextureBlock
  File "../blender/2.82/scripts/addons/SourceIO/source2/blocks/texture_data_block.py", line 8, in <module>
    from ..utils.PySourceIOUtils import *
ImportError: dynamic module does not define module export function (PyInit_PySourceIOUtils)
```

**Comment by REDxEYE** [comment]
No idea on this error

**Comment by mirh** [comment]
I mean.. it seems natural that if I'm replacing a file named `PySourceIOUtils` with one that originally came like `PySourceIOTextureUtils`, some function may be referenced differently.

**Comment by REDxEYE** [comment]
Oh, yem i forgot that i renamed it not to long ago

**Comment by TheClonerx** [comment]
One solution would be to provide two modules, one for 3.7 and for 3.8, and import according to the interpreter version.
```py
import sys
if (3, 8, 0) <= sys.version_info < (3, 9, 0) :
    from ..utils.PySourceIOUtils38 import *
elif (3, 7, 0) <= sys.version_info < (3, 8, 0):
    from ..utils.PySourceIOUtils37 import *
else:
    raise RuntimeError("Python version not yet supported: " + sys.version)
```
