### ISSUE TITLE
Issue when importing

### ISSUE THREAD

**Issue by Serial-cmd** [REDxEYE/SourceIO#331]
I have an issue importing a model from garry's mod. Here's the log:

SourceIO only support blender 4.X.X
Registered nodes
[WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*
[INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("D:/SteamLibrary/steamapps/common/GarrysMod/garrysmod/garrysmod")
[WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*
[DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: mod_write
[DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: default_write_path
[DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod'] as is not one of supported mount types: game_write
[DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod/download'] as is not one of supported mount types: download
[INFO]--[ContentManager:scan_for_content]: Mounted: Source1GameInfoProvider("D:/SteamLibrary/steamapps/common/GarrysMod/garrysmod/garrysmod/gameinfo.txt")
[INFO]--[MDL loader:import_model]: Trying to load model: D:/SteamLibrary/steamapps/common/GarrysMod/bin/gmpublisher/models/murderdrones/crek/n.mdl
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:48
Traceback (most recent call last):
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 54, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\models\__init__.py", line 25, in import_model
    steam_id = content_provider.get_steamid_from_asset(model_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\shared\content_manager\manager.py", line 68, in get_steamid_from_asset
    if provider := child.get_steamid_from_asset(asset_path):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 35, in get_steamid_from_asset
    if self.check(asset_path):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 20, in check
    if mount.check(filepath):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anaxia\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\shared\content_manager\providers\loose_files.py", line 12, in check
    if filepath.is_absolute():
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_absolute'

**Comment by Serial-cmd** [comment]
Nvm, compiled the model to ver 52 and worked, textures and everything

**Comment by REDxEYE** [comment]
v52 is a titanfall version. There is no compilers that can output this version

**Comment by iMaCHVFX** [comment]
SourceIO only support blender 4.X.X                                                                                                                                                                             Registered nodes                                                                                                                                                                                                Modules Installed (SourceIO) from 'C:\\Users\\iMaCH\\Downloads\\SourceIO.zip' into 'C:\\Users\\iMaCH\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons'                                      [WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*                                                                                                               [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/garrysmod_dir.vpk")                                                         [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_textures_dir.vpk")                                                   [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_sound_vo_english_dir.vpk")                                           [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_sound_misc_dir.vpk")                                                 [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_misc_dir.vpk")                                                       [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod")                                                                    [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine")                                                                 [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/download")                                                           [WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*                                                                                                               [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/platform/platform_misc_dir.vpk")                                                      [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/platform")                                                                     [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: mod_write                                                                                  [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: default_write_path                                                                         [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod'] as is not one of supported mount types: game_write                                                                                        [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod/download'] as is not one of supported mount types: download                                                                                 Traceback (most recent call last):                                                                                                                                                                                File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 45, in execute                                                 content_manager.scan_for_content(directory)                                                                                                                                                                   File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\manager.py", line 102, in scan_for_content                                             providers = detect_game(scan_path)                                                                                                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                            File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\detectors\__init__.py", line 28, in detect_game                                        results = detector.scan(path)                                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                 File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\detectors\gmod.py", line 31, in scan                                                   cls.add_provider(Source1GameInfoProvider(garrysmod_mod_gi_path), providers)                                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                               File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 44, in __init__                          with FileBuffer(filepath, "r") as f:                                                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\utils\file_utils.py", line 323, in __init__                                                                   io.FileIO.__init__(self, file, mode, closefd, opener)                                                                                                                                                       FileNotFoundError: [Errno 2] No such file or directory: TinyPath("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/garrysmod/gameinfo.txt")                                                    [WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*                                                                                                               [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/garrysmod_dir.vpk")                                                         [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_textures_dir.vpk")                                                   [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_sound_vo_english_dir.vpk")                                           [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_sound_misc_dir.vpk")                                                 [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine/hl2_misc_dir.vpk")                                                       [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod")                                                                    [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/sourceengine")                                                                 [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/download")                                                           [WARNING]--[GameInfoProvider:__init__]: Wildcard search path is not supported: garrysmod/addons/*                                                                                                               [INFO]--[GameInfoProvider:__init__]: Mounted: VPKContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/platform/platform_misc_dir.vpk")                                                      [INFO]--[GameInfoProvider:__init__]: Mounted: LooseFilesContentProvider("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/platform")                                                                     [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: mod_write                                                                                  [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['|gameinfo_path|.'] as is not one of supported mount types: default_write_path                                                                         [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod'] as is not one of supported mount types: game_write                                                                                        [DEBUG]--[GameInfoProvider:__init__]: Skipping mounting ['garrysmod/download'] as is not one of supported mount types: download                                                                                 Traceback (most recent call last):                                                                                                                                                                                File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 45, in execute                                                 content_manager.scan_for_content(directory)                                                                                                                                                                   File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\manager.py", line 102, in scan_for_content                                             providers = detect_game(scan_path)                                                                                                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                            File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\detectors\__init__.py", line 28, in detect_game                                        results = detector.scan(path)                                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                 File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\detectors\gmod.py", line 31, in scan                                                   cls.add_provider(Source1GameInfoProvider(garrysmod_mod_gi_path), providers)                                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                               File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\shared\content_manager\providers\source1_gameinfo_provider.py", line 44, in __init__                          with FileBuffer(filepath, "r") as f:                                                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                File "C:\Users\iMaCH\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\library\utils\file_utils.py", line 323, in __init__                                                                   io.FileIO.__init__(self, file, mode, closefd, opener)                                                                                                                                                       FileNotFoundError: [Errno 2] No such file or directory: TinyPath("C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/garrysmod/gameinfo.txt")




im pretty new to submitting issues here on github, so not sure the ettiquet. but this is the only thing i have found even remotely related to my issue so i figured commenting here might be my best bet.

all im trying to do is import a .mdl file i got from an addon in gmod

**Comment by Serial-cmd** [comment]
What blender version are you use?

**Comment by Serial-cmd** [comment]
Using*

**Comment by iMaCHVFX** [comment]
I'm using blender 4.3

**Comment by Serial-cmd** [comment]
Importing models only at the time works with 4.2 iirc

**Comment by iMaCHVFX** [comment]
oooooh thats very good to know! many thanks!

i will see if that fixes it for me later today!

**Comment by REDxEYE** [comment]
The error @iMaCHVFX having is not related to Blender 4.3. It's a bug in SourceIO 5.4.6, in 5.4.7 it was fixed, but .7 is not yet released as i didnt finish all the planned features but it already stable enought to be used in Blender 4.3

**Comment by Serial-cmd** [comment]
Oh, my bad
