### ISSUE TITLE
Unable to import models/maps

### ISSUE THREAD

**Issue by EditaNEmilis** [REDxEYE/SourceIO#334]
Trying to import some .mdl and .bsp from the Half-Life Project Beta Megabuild.
But guess it didn't work out and spew out some errors.

_First the model:_

```[INFO]--[MDL loader:import_model]: Trying to load model: D:/Program Files/hl2beta/hl2/models/Weapons/w_ar1.mdl
[INFO]--[MDL loader:import_model]: Detected magic: b'IDST', version:37
Traceback (most recent call last):
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 54, in execute
    model_container = import_model(mdl_path, f, content_manager, self, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\models\__init__.py", line 31, in import_model
    container = handler(model_path, buffer, content_provider, options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\models\mdl44\__init__.py", line 34, in import_mdl44
    mdl = MdlV44.from_buffer(buffer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\models\mdl\v44\mdl_file.py", line 62, in from_buffer
    bone = Bone.from_buffer(buffer, header.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\models\mdl\structs\bone.py", line 177, in from_buffer
    name = buffer.read_source1_string(start_offset) or "NO_NAME"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 38, in read_source1_string
    with self.read_from_offset(entry + offset):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 31, in read_from_offset
    self.seek(offset)
OSError: [Errno 22] Invalid argument
```

_And the map:_

```[INFO]--[d1_under_04bb.bsp:import_bsp]: Loading map "D:/Program Files/hl2beta/hl2_2003/maps/d1_under_04bb.bsp"
[WARNING]--[d1_under_04bb.bsp:import_entities]: Unrecognized game! Using default behaviour for handing entities, this may not work!
[INFO]--[d1_under_04bb.bsp:import_entities]: Using BaseEntityHandler entity handler
[INFO]--[Entity Lump:parse]: Detected 'ascii' encoding in entity lump
Traceback (most recent call last):
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 97, in execute
    import_bsp(filepath, f, content_manager, self,
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 56, in import_bsp
    import_entities(bsp, content_manager, settings, master_collection, logger)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 101, in import_entities
    entity_handler.load_entities(settings)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 98, in load_entities
    if not self.handle_entity(entity_data):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 112, in handle_entity
    handler_function(entity_object, entity_data)
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\base_entity_handler.py", line 291, in handle_worldspawn
    world = self._load_brush_model(0, 'world_geometry')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\source1\bsp\entities\abstract_entity_handlers.py", line 145, in _load_brush_model
    bsp_faces: list[Face] = self._bsp.get_lump('LUMP_FACES').faces
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\source1\bsp\bsp_file.py", line 93, in get_lump
    parsed_lump = self.parse_lump(sub, dep.lump_id, dep.lump_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\source1\bsp\bsp_file.py", line 128, in parse_lump
    parsed_lump = lump_class(lump_info).parse(buffer, self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\source1\bsp\lumps\face_lump.py", line 18, in parse
    self.faces.append(Face.from_buffer(buffer, self.version, bsp))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\source1\bsp\datatypes\face.py", line 56, in from_buffer
    lightmap_texture_size_in_luxels = buffer.read_fmt("2i")
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raman\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 241, in read_fmt
    data = struct.unpack_from(self._endian + fmt, self._buffer, self._offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack_from requires a buffer of at least 736780 bytes for unpacking 8 bytes at offset 736772 (actual buffer size is 736776)
```

**Comment by REDxEYE** [comment]
Closing due to lack of comunication
