### ISSUE TITLE
Error when importing Half-Life 1 '.bsp'

### ISSUE THREAD

**Issue by techsideofficial** [REDxEYE/SourceIO#338]
`Traceback (most recent call last):
  File "C:\Users\wiene\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\operators\goldsrc_operators.py", line 45, in execute
    bsp.load_map()
  File "C:\Users\wiene\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 107, in load_map
    self.load_entities()
  File "C:\Users\wiene\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\SourceIO\blender_bindings\goldsrc\bsp\import_bsp.py", line 251, in load_entities
    wad_file = self.bsp_file.manager.find_path(game_wad_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ContentManager' object has no attribute 'find_path'. Did you mean: 'filepath'?`

map is t0a0.bsp in Half Life

**Comment by REDxEYE** [comment]
Fixed here https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by techsideofficial** [comment]
Thanks, fixed
