### ISSUE TITLE
can't import materials

### ISSUE THREAD

**Issue by RandomChillGuy** [REDxEYE/SourceIO#339]
> Python: Traceback (most recent call last):
>   File "C:\Users\Sam\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 235, in execute
>     else:
> ^^^^^^^^^^
>   File "C:\Users\Sam\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 45, in create_material
>     handler: Source1ShaderBase = self._handlers.get(self.vmt.shader, Source1ShaderBase)(self.content_manager,
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Sam\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\material_loader\shaders\source1_shaders\vertexlit_generic.py", line 195, in create_nodes
>     @property
>            ^^^
>   File "C:\Users\Sam\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\SourceIO\blender_bindings\material_loader\shader_base.py", line 279, in create_nodes
>     self.bpy_material.use_screen_refraction = False
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Material' object has no attribute 'shadow_method'

**Comment by LoveRenamon** [comment]
#332 dupe
Switch to supported LTS version
