### ISSUE TITLE
Cannot import name "NonSourceInstall"

### ISSUE THREAD

**Issue by ReubenU** [REDxEYE/SourceIO#49]
When I try to install and activate the addon, Blender presents me with the error message below:

```
Traceback (most recent call last):
  File "/snap/blender/41/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/__init__.py", line 23, in <module>
    from .source1_operators import (BSPImport_OT_operator,
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1_operators.py", line 8, in <module>
    from .source1.vtf.blender_material import BlenderMaterial
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/blender_material.py", line 4, in <module>
    from ..vtf.vmt import VMT
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/vmt.py", line 3, in <module>
    from ...utilities.path_utilities import NonSourceInstall
ImportError: cannot import name 'NonSourceInstall' from 'SourceIO-master.utilities.path_utilities' (/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/utilities/path_utilities.py)
```

Operating System: Linux Mint 19.3 Tricia (MATE Desktop)
Blender Version: 2.83.2
Installation: snapd

**Comment by REDxEYE** [comment]
Cannot reproduce :C
