### ISSUE TITLE
Cannot Find File "libtxc_dxtn.so"

### ISSUE THREAD

**Issue by ReubenU** [REDxEYE/SourceIO#50]
I tried to uninstall and reinstall with the current version, and this error came up:

```
Traceback (most recent call last):
  File "/snap/blender/41/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/__init__.py", line 23, in <module>
    from .source1_operators import (BSPImport_OT_operator,
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1_operators.py", line 8, in <module>
    from .source1.vtf.blender_material import BlenderMaterial
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/blender_material.py", line 5, in <module>
    from ..vtf.import_vtf import import_texture
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/import_vtf.py", line 6, in <module>
    from ..vtf.VTFWrapper import VTFLib
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/VTFWrapper/VTFLib.py", line 40, in <module>
    class VTFLib:
  File "/home/rjunicruz/.config/blender/2.83/scripts/addons/SourceIO-master/source1/vtf/VTFWrapper/VTFLib.py", line 44, in VTFLib
    vtflib_cdll = cdll.LoadLibrary(os.path.join(full_path, vtf_lib_name))
  File "/snap/blender/41/2.83/python/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/snap/blender/41/2.83/python/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtxc_dxtn.so: cannot open shared object file: No such file or directory
```

Operating System: Linux Mint 19.3 Tricia (MATE Desktop)
Blender Version: 2.83.2
Installation: snapd

**Comment by REDxEYE** [comment]
duplication of #15

**Comment by ReubenU** [comment]
> duplication of #15

Can you close this?

**Comment by ReubenU** [comment]
Nvm I just found the button lol.
