### ISSUE TITLE
Mysterious Stereo Flexes Error

### ISSUE THREAD

**Issue by ReubenU** [REDxEYE/SourceIO#52]
I am not entirely sure what the error being thrown at me is correct because the model imported normally. Is this a case of model versions/formats?

```
Traceback (most recent call last):
  File "/home/rjunicruz/Desktop/blender-2.83.2-linux64/2.83/scripts/addons/SourceIO-master/source1_operators.py", line 58, in execute
    mdl, vvd, vtx = import_model(directory / file.name, vvd, vtx, phy, self.create_flex_drivers)
  File "/home/rjunicruz/Desktop/blender-2.83.2-linux64/2.83/scripts/addons/SourceIO-master/source1/new_model_import.py", line 208, in import_model
    name: str = mdl.get_value('stereo_flexes')[flex.flex_desc_index]
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1
```

Operating System: Linux Mint 19.3 Tricia (MATE Desktop)
Blender Version: 2.83.2
Installation: zipped folder

**Comment by REDxEYE** [comment]
It was already fixed in latest commit

**Comment by ReubenU** [comment]
Ok
