### ISSUE TITLE
Failure to import maps (.bsp)

### ISSUE THREAD

**Issue by Xiarno** [REDxEYE/SourceIO#63]
Windows 10
Blender version: 2.90.1

When I try to import an map (.bsp), I get this error:

```
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1_operators.py", line 105, in execute
    model = BSP(self.filepath)
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\import_bsp.py", line 60, in __init__
    self.map_file.parse()
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\bsp_file.py", line 29, in parse
    self.parse_lumps()
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\bsp_file.py", line 32, in parse_lumps
    self.parse_lump(VertexLump)
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\bsp_file.py", line 51, in parse_lump
    self.lumps[lump_class.lump_id] = lump_class(self).parse()
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\lump.py", line 121, in __init__
    super().__init__(bsp)
  File "D:\SteamLibrary\steamapps\common\Blender\2.90\scripts\addons\SourceIO\source1\bsp\lump.py", line 111, in __init__
    self.reader = ByteIO(byte_object=self._bsp.reader.read_bytes(self._lump.size))
TypeError: __init__() got an unexpected keyword argument 'byte_object'

location: <unknown location>:-1
```

**Comment by REDxEYE** [comment]
BSP import is WIP, issue about BSP will be ignored for now
