### ISSUE TITLE
Can't import MDLs, "NotImplementedError: Invalid VVD magic !"

### ISSUE THREAD

**Issue by Mimisor7** [REDxEYE/SourceIO#68]
When i try importing an MDL in blender, the model doesn't show up in the scene at all, and gives me this error message:

Traceback (most recent call last):
  File "C:\Users\censoredforgh\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO\source1_operators.py", line 58, in execute
    mdl, vvd, vtx = import_model(directory / file.name, vvd, vtx, phy, self.create_flex_drivers)
  File "C:\Users\censoredforgh\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO\source1\new_model_import.py", line 147, in import_model
    vvd.read()
  File "C:\Users\censoredforgh\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO\source1\new_vvd\vvd.py", line 48, in read
    self.header.read(self.reader)
  File "C:\Users\censoredforgh\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO\source1\new_vvd\structs\header.py", line 21, in read
    raise NotImplementedError('Invalid VVD magic {}!'.format(self.id))
NotImplementedError: Invalid VVD magic !

location: <unknown location>:-1

**Comment by REDxEYE** [comment]
Upload the model please

**Comment by Mimisor7** [comment]
Sorry for the late reply, here it is, it's Soldier from Team Fortress 2, i used GCFScape to extract it.

https://drive.google.com/file/d/1rchWvrZQvPWQUZ-d-tbOxBldCbkE7cTL/view?usp=sharing

**Comment by REDxEYE** [comment]
I need all 3 files vvd dx90.vtx mdl

**Comment by Mimisor7** [comment]
forgot to extract those in the same folder, closing issue
