### ISSUE TITLE
Error importing Dota's .vmdl_c and .vmat_c

### ISSUE THREAD

**Issue by AwesomeRomchik** [REDxEYE/SourceIO#74]
Hello, REDxEYE!
I'm trying to import some Dota models into blender
When importing .vmdl i get the following error:

`Traceback (most recent call last):
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2_operators.py", line 37, in execute
    model.load_mesh(self.invert_uv)
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2\resouce_types\valve_model.py", line 52, in load_mesh
    data_block = self.valve_file.get_data_block(block_name='DATA')[0]
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2\source2.py", line 78, in get_data_block
    block.read()
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2\blocks\data_block.py", line 21, in read
    ntro = self._valve_file.get_data_block(block_name="NTRO")[0]
IndexError: list index out of range

location: <unknown location>:-1
`

And this when importing .vmat:

`Traceback (most recent call last):
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2_operators.py", line 114, in execute
    material.load(self.flip, self.split_alpha)
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\SourceIO-master\source2\resouce_types\valve_material.py", line 30, in load
    textures[tex['m_name']] = tex_file, rgb_tex_name, alpha_tex_name
KeyError: 'm_name'

location: <unknown location>:-1
`

This happens with any model I've tried so far. Using Blender 2.90

**Comment by REDxEYE** [comment]
Dota 2 got an update that broke everything I wrote for it.
In simple words: SourceIO does not support Dota 2

**Comment by AwesomeRomchik** [comment]
Oh I understand, thank you!
