### ISSUE TITLE
Addon doesn't start on linux

### ISSUE THREAD

**Issue by EntityinArray** [REDxEYE/SourceIO#88]
Hello, thank you for working on this amazing project.
I have ran into a problem using this addon on a linux machine. Addon throws an error when enabled, that possibly has something to do with invocation of a DLL lzham_x64.

OS: Arch Linux
Blender 2.92.0

```
Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/__init__.py", line 29, in <module>
    from .source1_operators import (BSPImport_OT_operator,
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source1_operators.py", line 7, in <module>
    from .bpy_utilities.material_loader.material_loader import Source1MaterialLoader
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/bpy_utilities/material_loader/material_loader.py", line 8, in <module>
    from ...source1.vmt.valve_material import VMT
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source1/vmt/valve_material.py", line 1, in <module>
    from ...source_shared.content_manager import ContentManager
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source_shared/content_manager.py", line 7, in <module>
    from ..source_shared.vpk_sub_manager import VPKContentProvider
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source_shared/vpk_sub_manager.py", line 3, in <module>
    from .vpk.vpk_file import open_vpk
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source_shared/vpk/__init__.py", line 1, in <module>
    from .vpk_file import VPKFile
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/source_shared/vpk/vpk_file.py", line 9, in <module>
    from ...utilities.thirdparty.lzham.lzham import LZHAM
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/utilities/thirdparty/lzham/lzham.py", line 49, in <module>
    class LZHAM(metaclass=SingletonMeta):
  File "/home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/utilities/thirdparty/lzham/lzham.py", line 50, in LZHAM
    lib = CDLL(str(Path(__file__).parent / 'lzham_x64'))
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/entityinarray/.config/blender/2.92/scripts/addons/SourceIO/utilities/thirdparty/lzham/lzham_x64: cannot open shared object file: No such file or directory
```

I would appreciate any help, thank you.

**Comment by REDxEYE** [comment]
Try big_update branch, i've added unix LZHAM library there

**Comment by EntityinArray** [comment]
Amazing, thank you!

**Comment by SunbroJedi** [comment]
How do I download from a specific branch? I went to the big_update branch, but when I click releases, it goes back to the master branch.

**Comment by REDxEYE** [comment]
Download repository itself, not a release. Big update isn't released yet

**Comment by SunbroJedi** [comment]
oh ok.

**Comment by SunbroJedi** [comment]
I still get an error
![image](https://user-images.githubusercontent.com/55336959/117079510-e4363200-ad09-11eb-8495-a6f71ec0dfbb.png)

**Comment by REDxEYE** [comment]
You need to install the nvidia texture compression library

**Comment by SunbroJedi** [comment]
Even if I'm not using a nvidia card?

**Comment by REDxEYE** [comment]
Yes

**Comment by SunbroJedi** [comment]
oh ok

**Comment by SunbroJedi** [comment]
What's the library called and how do I download it?

**Comment by REDxEYE** [comment]
https://packages.debian.org/ru/jessie/libtxc-dxtn-s2tc0 or https://github.com/nobled/libtxc_dxtn

**Comment by SunbroJedi** [comment]
New error 
![image](https://user-images.githubusercontent.com/55336959/117080305-8f93b680-ad0b-11eb-8b94-34f316da903e.png)

**Comment by REDxEYE** [comment]
I don't know anything about this library, google yourself. There so many linux distros, I cannot provide support for each and everyone version of it

**Comment by headassbtw** [comment]
I'm having this issue as well, except i can't seem to find the menitioned "big update" branch, this happens with the latest release i stopped trying about 4 updates back

**Comment by headassbtw** [comment]
nevermind, installed libxtc_dxtn from the AUR and it loads fine

**Comment by Jmvars** [comment]
Downloading repo directly worked. Thanks <3

**Comment by Pegacy** [comment]
On MacOS too. How install this library?
`Traceback (most recent call last):
  File "/Applications/Blender 2.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/__init__.py", line 18, in <module>
    from .blender_bindings import register, unregister
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/blender_bindings/__init__.py", line 6, in <module>
    from .operators.goldsrc_operators import (SOURCEIO_OT_GBSPImport,
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/blender_bindings/operators/goldsrc_operators.py", line 8, in <module>
    from ..goldsrc import import_model
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/blender_bindings/goldsrc/__init__.py", line 4, in <module>
    from ..goldsrc.mdl_v4.import_mdl import import_model as import_model_v4
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/blender_bindings/goldsrc/mdl_v4/import_mdl.py", line 13, in <module>
    from ...shared.model_container import GoldSrcV4ModelContainer
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/blender_bindings/shared/model_container.py", line 8, in <module>
    from ...library.source2.resource_types import ValveCompiledModel
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/source2/resource_types/__init__.py", line 1, in <module>
    from .resource import ValveCompiledResource
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/source2/resource_types/resource.py", line 4, in <module>
    from ..data_blocks import DATA
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/source2/data_blocks/__init__.py", line 2, in <module>
    from .mrph_block import MRPH
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/source2/data_blocks/mrph_block.py", line 3, in <module>
    from .data_block import DATA
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/source2/data_blocks/data_block.py", line 2, in <module>
    from ...utils.binary_keyvalue import BinaryKeyValue
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/utils/binary_keyvalue.py", line 7, in <module>
    from ..utils.thirdparty.lz4_wrapper import LZ4ChainDecoder, LZ4Wrapper
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/utils/thirdparty/lz4_wrapper/__init__.py", line 45, in <module>
    class LZ4Wrapper:
  File "/Users/alexpc/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/library/utils/thirdparty/lz4_wrapper/__init__.py", line 46, in LZ4Wrapper
    lib_cdll: ctypes.CDLL = load_library(Path(__file__).parent / lz4_libname)
NameError: name 'lz4_libname' is not defined

`

**Comment by REDxEYE** [comment]
@Pegacy  M1 MacOS?

**Comment by Pegacy** [comment]
> @Pegacy M1 MacOS?

MacOs Catalina 10.15.7 MacbookPro Retina 13 e2015. Intel core i5 2.7ghz

**Comment by REDxEYE** [comment]
Okay, in you case, MacOS was support was never implemented for LZ4 wrapper, you'll need to wait for update where I add missing library

**Comment by Pegacy** [comment]
> Okay, in you case, MacOS was support was never implemented for LZ4 wrapper, you'll need to wait for update where I add missing library

Thanks! Please write in this thread when it's done.

**Comment by Pegacy** [comment]
> Okay, in you case, MacOS was support was never implemented for LZ4 wrapper, you'll need to wait for update where I add missing library

OMG, you amazing! It works. Thanks!

**Comment by REDxEYE** [comment]
Texture import library was only compiled for MacOS Intel x64 arch, not M1 arm64 arch

**Comment by BorboBorgo** [comment]
I had a similar issue regarding the textures, if all else fails try installing this library https://packages.debian.org/stretch/amd64/libtxc-dxtn-s2tc/download or compiling this one https://github.com/nobled/libtxc_dxtn , the first one worked for me!
