### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by coryanimations** [REDxEYE/SourceIO#91]
When I try to use this addon for Blender on my Mac it gives me an error. I'm assuming this is because something about the addon is PC exclusive. If there is any way you could make this work for Mac that would be much appreciated.

**Comment by coryanimations** [comment]
![Screen Shot 2021-05-28 at 10 45 15 PM](https://user-images.githubusercontent.com/84861027/120057194-cd33e880-c006-11eb-84d3-6547a6c021a3.png)

**Comment by ddomino007** [comment]
I've never had this happen with a plugin before, happens only on source. It clearly has a defined value on which os is supported. Is there a reason for that distinction? Has the developer forgotten about it?  (Since they asked for logs when it's simply a something by their design)

**Comment by REDxEYE** [comment]
VTFLib isn't supported on MacOS, I will implement a workaround that just turns off support for VTF in addon

**Comment by REDxEYE** [comment]
Please check if commit 9f7bc83 fixes your issue

**Comment by ddomino007** [comment]
it does not
https://youtu.be/Qtvv02bfZRE <-
`
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/benji/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-9f7bc8315d1e1a5f48cf4255e3aa5a1346f0a73b/__init__.py", line 4, in <module>
    from SourceIO.source1.vtf import is_vtflib_supported
ModuleNotFoundError: No module named 'SourceIO'
`

**Comment by REDxEYE** [comment]
Give me a sec to fix it

**Comment by REDxEYE** [comment]
Please try again

**Comment by ddomino007** [comment]
still nothing
https://youtu.be/wGQTZciS2O4 <-
```
Read prefs: /Users/benji/Library/Application Support/Blender/2.93/config/userpref.blend
addon_utils.disable: SourceIO-master not disabled
Modules Installed (SourceIO-master) from '/Users/benji/Desktop/SourceIO-master.zip' into '/Users/benji/Library/Application Support/Blender/2.93/scripts/addons'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/benji/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/__init__.py", line 5, in <module>
    from .source1.vtf.VTFWrapper.VTFLib import VTFLib
  File "/Users/benji/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source1/vtf/VTFWrapper/VTFLib.py", line 32, in <module>
    raise UnsupportedOS(f"{platform_name} is not supported")
SourceIO-master.source1.vtf.VTFWrapper.VTFLib.UnsupportedOS: Darwin is not supported
```

**Comment by REDxEYE** [comment]
Thanks for helping me troubleshoot it. I pushed another small fix. I'll check this thread tomorrow.

**Comment by ddomino007** [comment]
sorry I think I misunderstood, you want me to try the latest commit? okay, I'll let you know my findings

**Comment by REDxEYE** [comment]
Yes

**Comment by ddomino007** [comment]
```

addon_utils.disable: SourceIO-master not disabled
Modules Installed (SourceIO-master) from '/Users/benji/Downloads/SourceIO-master.zip' into '/var/root/Library/Application Support/Blender/2.93/scripts/addons'
Using BPY logger
PySourceIOTextureUtils import error
Failed to import native binary!
Using python version
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/__init__.py", line 26, in <module>
    from .goldsrc_operators import (GBSPImport_OT_operator,
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/goldsrc_operators.py", line 6, in <module>
    from .goldsrc.bsp.import_bsp import BSP
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/goldsrc/bsp/import_bsp.py", line 9, in <module>
    from .entity_handlers import entity_handlers
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/goldsrc/bsp/entity_handlers.py", line 8, in <module>
    from ..mdl.import_mdl import import_model
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/goldsrc/mdl/import_mdl.py", line 12, in <module>
    from ...source_shared.model_container import GoldSrcModelContainer
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source_shared/model_container.py", line 7, in <module>
    from ..source2.resouce_types.valve_model import ValveCompiledModel
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source2/resouce_types/valve_model.py", line 11, in <module>
    from .valve_material import ValveCompiledMaterial
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source2/resouce_types/valve_material.py", line 10, in <module>
    from ...bpy_utilities.material_loader.material_loader import Source2MaterialLoader
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/bpy_utilities/material_loader/material_loader.py", line 11, in <module>
    from .shaders.source1_shader_base import Source1ShaderBase
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/bpy_utilities/material_loader/shaders/source1_shader_base.py", line 7, in <module>
    from ....source1.vtf.import_vtf import import_texture
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source1/vtf/import_vtf.py", line 4, in <module>
    from ..vtf.VTFWrapper import VTFLib
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/SourceIO-master/source1/vtf/VTFWrapper/VTFLib.py", line 32, in <module>
    raise UnsupportedOS(f"{platform_name} is not supported")
SourceIO-master.source1.vtf.VTFWrapper.VTFLib.UnsupportedOS: Darwin is not supported
```

**Comment by REDxEYE** [comment]
Can you please try again?

**Comment by ddomino007** [comment]
it enables now without a problem. importing random example I found on sfmlab worked.
[here's the map I tried](https://sfmlab.com/project/file/download/37181/ams1/)

**Comment by REDxEYE** [comment]
That's good, keep testing and close ticket if everything behaves as expected
